# Generated by Django 6.0.4 on 2026-05-04 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0020_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPaymentSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('amount', models.PositiveBigIntegerField(db_index=True)),
                ('balance', models.PositiveBigIntegerField()),
                ('sms_datetime', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('MATCHED', 'Matched'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed'), ('NO_MATCH', 'No match')], db_index=True, default='NEW', max_length=20)),
                ('matched_orders', models.ManyToManyField(blank=True, related_name='incoming_payment_sms', to='store.order')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='payments_in_status_00ea11_idx'), models.Index(fields=['amount', 'sms_datetime'], name='payments_in_amount_2cfb1c_idx')],
            },
        ),
    ]
