# Generated by Django 6.0.4 on 2026-05-04 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('store', '0021_alter_botconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingpaymentsms',
            options={'ordering': ['-received_at'], 'verbose_name': 'incoming payment SMS', 'verbose_name_plural': 'incoming payment SMS messages'},
        ),
        migrations.AlterField(
            model_name='incomingpaymentsms',
            name='amount',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='incomingpaymentsms',
            name='balance',
            field=models.PositiveBigIntegerField(verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='incomingpaymentsms',
            name='matched_orders',
            field=models.ManyToManyField(blank=True, help_text='Orders that match this SMS by amount and payment time window.', related_name='incoming_payment_sms', to='store.order', verbose_name='matched orders'),
        ),
        migrations.AlterField(
            model_name='incomingpaymentsms',
            name='raw_text',
            field=models.TextField(help_text='Original text received from the bank SMS.', verbose_name='raw text'),
        ),
        migrations.AlterField(
            model_name='incomingpaymentsms',
            name='received_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='received at'),
        ),
        migrations.AlterField(
            model_name='incomingpaymentsms',
            name='sms_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='SMS datetime'),
        ),
        migrations.AlterField(
            model_name='incomingpaymentsms',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('MATCHED', 'Matched'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed'), ('NO_MATCH', 'No match')], db_index=True, default='NEW', help_text='Current matching and confirmation state for this incoming payment SMS.', max_length=20, verbose_name='status'),
        ),
    ]
