# Generated by Django 6.0.4 on 2026-05-02 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن (مثلا ۵۰ گیگ یک ماهه)')),
                ('volume_gb', models.IntegerField(verbose_name='حجم به گیگابایت')),
                ('duration_days', models.IntegerField(verbose_name='مدت زمان به روز')),
                ('price', models.IntegerField(verbose_name='قیمت (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال برای فروش؟')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('checking', 'در حال بررسی تراکنش'), ('activated', 'فعال شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('card_last_4', models.CharField(blank=True, max_length=4, null=True, verbose_name='چهار رقم آخر کارت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='تصویر فیش')),
                ('config_details', models.TextField(blank=True, null=True, verbose_name='لینک/متن کانفیگ (غیرفعال در ابتدا)')),
                ('client_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID کاربر در پنل سنایی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.plan', verbose_name='پلن انتخابی')),
            ],
        ),
    ]
