# Generated by Django 6.0.4 on 2026-05-02 11:56

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='آزادنت', max_length=100, verbose_name='نام فروشگاه')),
                ('english_name', models.CharField(default='AzadNet', max_length=100, verbose_name='نام انگلیسی')),
                ('card_number', models.CharField(help_text='بدون فاصله وارد کنید', max_length=16, verbose_name='شماره کارت برای واریز')),
                ('card_owner', models.CharField(max_length=100, verbose_name='نام صاحب کارت')),
                ('hero_title', models.CharField(default='اینترنت آزاد حق شماست', max_length=200, verbose_name='تیتر اصلی سایت')),
                ('hero_text', models.TextField(default='با آزادنت بدون محدودیت به دنیای وب متصل شوید.', verbose_name='متن توضیحات سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='card_last_4',
            new_name='card_last_four',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_uuid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='config_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='bank_tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پیگیری بانک'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tracking_code',
            field=models.CharField(default=store.models.generate_order_tracking, max_length=10, unique=True, verbose_name='کد پیگیری سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ساب'),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='admin', max_length=100, verbose_name='نام کاربری VPN'),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.plan', verbose_name='پلن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('pending_verification', 'در انتظار تایید رسید'), ('completed', 'تکمیل شده (فعال)'), ('rejected', 'رد شده')], default='pending_payment', max_length=30, verbose_name='وضعیت سفارش'),
        ),
    ]
