# Generated by Django 6.0.4 on 2026-05-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dirct_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
