# Generated by Django 6.0.4 on 2026-05-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_dirct_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dirct_link',
            new_name='direct_link',
        ),
    ]
