# Generated by Django 6.0.4 on 2026-05-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_dirct_link_order_direct_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پنل (مثال: سرور آلمان)')),
                ('url', models.URLField(verbose_name='آدرس کامل پنل (بدون اسلش آخر)')),
                ('username', models.CharField(max_length=100, verbose_name='نام کاربری پنل')),
                ('password', models.CharField(max_length=100, verbose_name='رمز عبور پنل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_channel',
            field=models.URLField(blank=True, null=True, verbose_name='لینک کانال تلگرام'),
        ),
        migrations.AddField(
            model_name='store',
            name='telegram_support',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آیدی پشتیبانی تلگرام'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام پلن (مثلا ۱ گیگ یک ماهه)'),
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_id', models.IntegerField(verbose_name='آیدی Inbound در پنل')),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMESS'), ('trojan', 'Trojan')], default='vless', max_length=20, verbose_name='پروتکل')),
                ('server_ip', models.CharField(max_length=100, verbose_name='آی\u200cپی یا دامنه سرور (برای کانفیگ)')),
                ('port', models.CharField(max_length=10, verbose_name='پورت اتصال')),
                ('config_params', models.CharField(max_length=255, verbose_name='پارامترهای کانفیگ (type=tcp&...)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال برای فروش')),
                ('current_users', models.IntegerField(default=0, verbose_name='تعداد کاربر فعلی')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='store.panel', verbose_name='پنل')),
            ],
        ),
    ]
