# Generated by Django 6.0.4 on 2026-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_panel_store_telegram_channel_store_telegram_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='fingerprint',
            field=models.CharField(blank=True, default='chrome', max_length=50, null=True, verbose_name='Fingerprint (fp)'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='network_type',
            field=models.CharField(default='tcp', max_length=20, verbose_name='نوع شبکه (tcp, ws, grpc)'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='pbk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Public Key (pbk)'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='security',
            field=models.CharField(default='none', max_length=20, verbose_name='امنیت (none, tls, reality)'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='sid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short ID (sid)'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='sni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دامنه SNI'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='ws_host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='هاست (host)'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='ws_path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مسیر (path)'),
        ),
    ]
