# Generated by Django 6.0.4 on 2026-05-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.inbound', verbose_name='اینباند'),
        ),
    ]
