# Generated by Django 6.0.4 on 2026-05-03 21:49

from datetime import timedelta
import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import store.models
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_model_architecture(apps, schema_editor):
    Store = apps.get_model('store', 'Store')
    Plan = apps.get_model('store', 'Plan')
    Panel = apps.get_model('store', 'Panel')
    Order = apps.get_model('store', 'Order')
    VPNClient = apps.get_model('store', 'VPNClient')

    first_store = Store.objects.order_by('id').first()

    for store_obj in Store.objects.all():
        update_fields = []
        if not store_obj.slug:
            store_obj.slug = f"store-{store_obj.id}"
            update_fields.append('slug')
        if update_fields:
            store_obj.save(update_fields=update_fields)

    for plan in Plan.objects.select_related('store'):
        update_fields = []
        if not plan.store_id and first_store:
            plan.store = first_store
            update_fields.append('store')
        if not plan.slug:
            plan.slug = f"plan-{plan.id}"
            update_fields.append('slug')
        if update_fields:
            plan.save(update_fields=update_fields)

    for panel in Panel.objects.all():
        if not panel.store_id and first_store:
            panel.store = first_store
            panel.save(update_fields=['store'])

    for order in Order.objects.select_related('plan', 'inbound'):
        update_fields = []

        if not order.public_id:
            order.public_id = uuid.uuid4()
            update_fields.append('public_id')

        if order.status == 'pending':
            order.status = 'pending_verification'
            update_fields.append('status')

        if not order.store_id:
            order.store = order.plan.store if order.plan and order.plan.store_id else first_store
            update_fields.append('store')

        if not order.amount and order.plan_id:
            order.amount = order.plan.price
            update_fields.append('amount')

        if not order.currency:
            order.currency = getattr(order.plan, 'currency', 'TOMAN') if order.plan_id else 'TOMAN'
            update_fields.append('currency')

        if not order.sender_card_last4 and order.card_last_four:
            order.sender_card_last4 = order.card_last_four
            update_fields.append('sender_card_last4')

        if order.status == 'completed':
            order.is_paid = True
            order.verification_status = 'verified'
            order.verified_at = order.verified_at or timezone.now()
            update_fields.extend(['is_paid', 'verification_status', 'verified_at'])
        elif order.status == 'rejected':
            order.verification_status = 'rejected'
            update_fields.append('verification_status')
        elif order.is_paid:
            order.status = 'pending_verification'
            order.verification_status = 'pending'
            order.payment_submitted_at = order.payment_submitted_at or order.created_at
            update_fields.extend(['status', 'verification_status', 'payment_submitted_at'])

        if update_fields:
            order.save(update_fields=sorted(set(update_fields)))

        if order.uuid:
            vpn_client, _ = VPNClient.objects.get_or_create(
                uuid=order.uuid,
                defaults={
                    'store': order.store,
                    'order': order,
                    'plan': order.plan,
                    'inbound': order.inbound,
                    'username': order.username or f"order-{order.order_tracking_code}",
                    'sub_link': order.sub_link,
                    'direct_link': order.direct_link,
                    'status': 'active' if order.status == 'completed' else 'inactive',
                    'traffic_limit_bytes': order.plan.volume_gb * 1024 * 1024 * 1024 if order.plan_id else 0,
                    'duration_days': order.plan.duration_days if order.plan_id else 0,
                    'device_limit': getattr(order.plan, 'device_limit', 2) if order.plan_id else 2,
                    'activated_at': order.verified_at if order.status == 'completed' else None,
                    'expires_at': (
                        order.verified_at + timedelta(days=order.plan.duration_days)
                        if order.status == 'completed' and order.verified_at and order.plan_id
                        else None
                    ),
                },
            )
            if not vpn_client.order_id:
                vpn_client.order = order
                vpn_client.save(update_fields=['order'])


def reverse_backfill_model_architecture(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_inbound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('public_id', models.UUIDField(default=store.models.generate_public_id, editable=False, unique=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('xui_email', models.CharField(blank=True, max_length=150)),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sub_id', models.CharField(blank=True, max_length=100)),
                ('sub_link', models.URLField(blank=True, max_length=500, null=True)),
                ('direct_link', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('error', 'Error')], db_index=True, default='created', max_length=20)),
                ('traffic_limit_bytes', models.PositiveBigIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=0)),
                ('device_limit', models.PositiveIntegerField(default=2)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('xui_raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='inbound',
            options={'ordering': ['panel__name', 'inbound_id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price', 'id']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='inbound',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='inbound',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='max_clients',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbound',
            name='remark',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='inbound',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('TOMAN', 'Toman'), ('IRR', 'Iranian Rial'), ('USD', 'US Dollar')], default='TOMAN', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('manual_card', 'Manual card-to-card'), ('gateway', 'Online gateway')], db_index=True, default='manual_card', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_card_last4',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Enter exactly 4 digits.', regex='^\\d{4}$')]),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_card_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='panel',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='store.store'),
        ),
        migrations.AddField(
            model_name='panel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('TOMAN', 'Toman'), ('IRR', 'Iranian Rial'), ('USD', 'US Dollar')], default='TOMAN', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='device_limit',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='store.store'),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='store',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='config_params',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='current_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='fingerprint',
            field=models.CharField(blank=True, default='chrome', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='inbound_id',
            field=models.PositiveIntegerField(help_text='Inbound ID in Sanaei/X-UI.'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='network_type',
            field=models.CharField(choices=[('tcp', 'TCP'), ('ws', 'WebSocket'), ('grpc', 'gRPC')], default='tcp', max_length=20),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='store.panel'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='pbk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='port',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='protocol',
            field=models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMESS'), ('trojan', 'Trojan')], default='vless', max_length=20),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='security',
            field=models.CharField(choices=[('none', 'None'), ('tls', 'TLS'), ('reality', 'Reality')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='server_ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='sid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='sni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='ws_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='ws_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bank_tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.inbound'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_tracking_code',
            field=models.CharField(db_index=True, default=store.models.generate_order_tracking, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.plan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('pending_verification', 'Pending verification'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='panel',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='panel',
            name='url',
            field=models.URLField(help_text='Full panel URL without trailing slash.'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Plan duration in days.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(help_text='Plan price in the selected currency.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='volume_gb',
            field=models.PositiveIntegerField(help_text='Traffic limit in GB.'),
        ),
        migrations.AlterField(
            model_name='store',
            name='card_number',
            field=models.CharField(help_text='Manual card-to-card destination card number, without spaces.', max_length=16),
        ),
        migrations.AlterField(
            model_name='store',
            name='card_owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='english_name',
            field=models.CharField(default='VPN Store', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='hero_text',
            field=models.TextField(default='Buy a VPN plan and receive your configuration after payment verification.'),
        ),
        migrations.AlterField(
            model_name='store',
            name='hero_title',
            field=models.CharField(default='Fast and secure VPN access', max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='VPN Store', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram_channel',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram_support',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='inbound',
            index=models.Index(fields=['panel', 'is_active'], name='store_inbou_panel_i_7c90e9_idx'),
        ),
        migrations.AddIndex(
            model_name='inbound',
            index=models.Index(fields=['protocol', 'network_type', 'security'], name='store_inbou_protoco_58a994_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status', 'created_at'], name='store_order_store_i_c164df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['verification_status', 'created_at'], name='store_order_verific_48e0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'payment_gateway'], name='store_order_payment_3726cb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['uuid'], name='store_order_uuid_0ee5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['store', 'is_active'], name='store_panel_store_i_1336dd_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['store', 'is_active', 'sort_order'], name='store_plan_store_i_8a1a71_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'slug'], name='store_store_is_acti_220478_idx'),
        ),
        migrations.AddConstraint(
            model_name='inbound',
            constraint=models.UniqueConstraint(fields=('panel', 'inbound_id'), name='unique_inbound_id_per_panel'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('store', 'slug'), name='unique_plan_slug_per_store'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_clients', to='store.inbound'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_client', to='store.order'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_clients', to='store.plan'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vpn_clients', to='store.store'),
        ),
        migrations.RunPython(
            backfill_model_architecture,
            reverse_backfill_model_architecture,
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(default=store.models.generate_public_id, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='vpnclient',
            index=models.Index(fields=['store', 'status'], name='store_vpncl_store_i_bdf824_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnclient',
            index=models.Index(fields=['inbound', 'status'], name='store_vpncl_inbound_867071_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnclient',
            index=models.Index(fields=['expires_at'], name='store_vpncl_expires_1b7149_idx'),
        ),
    ]
