# Generated by Django 6.0.4 on 2026-05-03 22:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import store.models
from django.conf import settings
from django.db import migrations, models


def backfill_order_amounts_and_xui_email(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    VPNClient = apps.get_model('store', 'VPNClient')

    for order in Order.objects.select_related('plan').all():
        original_amount = order.amount or (order.plan.price if order.plan_id else 0)
        Order.objects.filter(pk=order.pk).update(original_amount=original_amount)

    for client in VPNClient.objects.all():
        if client.xui_email or not client.uuid:
            continue
        prefix = client.username or 'client'
        xui_email = f"{prefix}_{str(client.uuid)[:8]}"
        VPNClient.objects.filter(pk=client.pk).update(xui_email=xui_email)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_vpnclient_alter_inbound_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=20)),
                ('value', models.PositiveIntegerField(help_text='Percentage value or fixed amount in the order currency.', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VPNClientUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_traffic_bytes', models.PositiveBigIntegerField(default=0)),
                ('used_upload_bytes', models.PositiveBigIntegerField(default=0)),
                ('used_download_bytes', models.PositiveBigIntegerField(default=0)),
                ('used_traffic_bytes', models.PositiveBigIntegerField(default=0)),
                ('remaining_traffic_bytes', models.PositiveBigIntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='original_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='last_online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='used_download_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='used_traffic_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='used_upload_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_tracking_code',
            field=models.CharField(db_index=True, default=store.models.generate_order_tracking, max_length=36, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid tracking code.', regex='^([A-Za-z0-9]{8}|[0-9a-fA-F]{32}|[0-9a-fA-F-]{36})$')]),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_clients', to='store.order'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='xui_email',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.RunPython(backfill_order_amounts_and_xui_email, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='vpnclient',
            index=models.Index(fields=['xui_email'], name='store_vpncl_xui_ema_37f3cc_idx'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to allow this code for every active plan.', related_name='discount_codes', to='store.plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.discountcode'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['discount_code', 'created_at'], name='store_order_discoun_757fda_idx'),
        ),
        migrations.AddField(
            model_name='vpnclientusagesnapshot',
            name='vpn_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='store.vpnclient'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['code', 'is_active'], name='store_disco_code_172874_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['valid_from', 'valid_until'], name='store_disco_valid_f_a0dbec_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnclientusagesnapshot',
            index=models.Index(fields=['vpn_client', 'recorded_at'], name='store_vpncl_vpn_cli_f0bb4e_idx'),
        ),
    ]
