# Generated by Django 6.0.4 on 2026-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_discountcode_vpnclientusagesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bale_support',
            field=models.CharField(blank=True, help_text='Bale support username, @username, or full ble.ir link.', max_length=200, null=True),
        ),
    ]
