# Generated by Django 6.0.4 on 2026-05-04 02:45

import django.db.models.deletion
import django.utils.timezone
import random
import string
from django.db import migrations, models


def backfill_customer_referral_codes(apps, schema_editor):
    Customer = apps.get_model('store', 'Customer')
    alphabet = string.ascii_uppercase + string.digits
    used_codes = set(Customer.objects.exclude(referral_code__isnull=True).exclude(referral_code='').values_list('referral_code', flat=True))

    for customer in Customer.objects.filter(referral_code__isnull=True):
        code = ''.join(random.choices(alphabet, k=8))
        while code in used_codes:
            code = ''.join(random.choices(alphabet, k=8))
        used_codes.add(code)
        customer.referral_code = code
        customer.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reward_type', models.CharField(choices=[('discount_20', '20% discount coupon'), ('free_1gb_plan', 'Free 1GB plan')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20)),
                ('milestone', models.PositiveIntegerField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral_code', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=20)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='store_plan_store_i_8a1a71_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='store.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Hide internal reward plans from the public plan selector when disabled.'),
        ),
        migrations.RunPython(backfill_customer_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['referral_code'], name='store_custo_referra_8adcca_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['referred_by', 'created_at'], name='store_custo_referre_d0d6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['store', 'is_active', 'is_public', 'sort_order'], name='store_plan_store_i_fb32fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('username', ''), _negated=True), fields=('username',), name='unique_customer_username_when_set'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', ''), _negated=True), fields=('phone_number',), name='unique_customer_phone_when_set'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='store.customer'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_rewards', to='store.discountcode'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_rewards', to='store.plan'),
        ),
        migrations.AddField(
            model_name='referral',
            name='first_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_conversions', to='store.order'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to='store.customer'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='store.customer'),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='store.referral'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status', 'created_at'], name='store_refer_referre_3e0cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code', 'status'], name='store_refer_referra_dac0bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('referrer', 'referred_customer'), name='unique_referral_pair'),
        ),
        migrations.AddIndex(
            model_name='customerreward',
            index=models.Index(fields=['customer', 'status', 'earned_at'], name='store_custo_custome_d9f4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreward',
            index=models.Index(fields=['reward_type', 'status'], name='store_custo_reward__40fa25_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerreward',
            constraint=models.UniqueConstraint(condition=models.Q(('referral__isnull', False)), fields=('customer', 'referral', 'reward_type'), name='unique_reward_per_referral_type'),
        ),
        migrations.AddConstraint(
            model_name='customerreward',
            constraint=models.UniqueConstraint(condition=models.Q(('milestone__isnull', False)), fields=('customer', 'reward_type', 'milestone'), name='unique_reward_per_referral_milestone'),
        ),
    ]
