# Generated by Django 6.0.4 on 2026-05-04 03:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customerreward_referral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='volume_gb',
            field=models.DecimalField(decimal_places=3, help_text='Traffic limit in GB. Use decimal values for small plans, e.g. 0.1 for 100 MB.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
