# Generated by Django 6.0.4 on 2026-05-04 03:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_plan_volume_gb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='Admin bot', max_length=100)),
                ('provider', models.CharField(choices=[('bale', 'Bale'), ('telegram', 'Telegram')], db_index=True, default='bale', max_length=20)),
                ('bot_token', models.CharField(help_text='Bot token from Bale or Telegram.', max_length=255)),
                ('admin_user_id', models.CharField(help_text='Admin chat/user ID that receives notifications.', max_length=80)),
                ('webhook_secret', models.CharField(default=store.models.generate_bot_webhook_secret, editable=False, max_length=32, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_order_updates', models.BooleanField(default=True)),
                ('send_sales_reports', models.BooleanField(default=True)),
                ('report_interval_hours', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('last_report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_configurations', to='store.store')),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BotEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('new_order', 'New order'), ('order_approved', 'Order approved'), ('order_rejected', 'Order rejected'), ('sales_report', 'Sales report'), ('webhook', 'Webhook'), ('error', 'Error')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('bot_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='store.botconfiguration')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_event_logs', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotPendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user_id', models.CharField(db_index=True, max_length=80)),
                ('action', models.CharField(choices=[('reject_order', 'Reject order')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('bot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='store.botconfiguration')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_pending_actions', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='botconfiguration',
            index=models.Index(fields=['provider', 'is_active'], name='store_botco_provide_d8ebbf_idx'),
        ),
        migrations.AddIndex(
            model_name='botconfiguration',
            index=models.Index(fields=['store', 'is_active'], name='store_botco_store_i_9edab3_idx'),
        ),
        migrations.AddIndex(
            model_name='boteventlog',
            index=models.Index(fields=['event_type', 'status', 'created_at'], name='store_botev_event_t_a9b9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='boteventlog',
            index=models.Index(fields=['bot_config', 'created_at'], name='store_botev_bot_con_b622de_idx'),
        ),
        migrations.AddIndex(
            model_name='boteventlog',
            index=models.Index(fields=['order', 'created_at'], name='store_botev_order_i_1502c0_idx'),
        ),
        migrations.AddIndex(
            model_name='botpendingaction',
            index=models.Index(fields=['bot_config', 'admin_user_id', 'status', 'created_at'], name='store_botpe_bot_con_058a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='botpendingaction',
            index=models.Index(fields=['order', 'status'], name='store_botpe_order_i_2303d2_idx'),
        ),
    ]
