# Generated by Django 6.0.4 on 2026-05-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_botconfiguration_boteventlog_botpendingaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boteventlog',
            name='event_type',
            field=models.CharField(choices=[('new_order', 'New order'), ('order_approved', 'Order approved'), ('order_rejected', 'Order rejected'), ('sales_report', 'Sales report'), ('webhook', 'Webhook'), ('callback', 'Callback'), ('error', 'Error')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('sent', 'Sent'), ('received', 'Received'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=20),
        ),
    ]
