# Generated by Django 6.0.4 on 2026-05-04 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_boteventlog_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('manual_card', 'Manual card-to-card'), ('gateway', 'Online gateway'), ('admin_free', 'Admin free subscription')], db_index=True, default='manual_card', max_length=30),
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_user_id', models.CharField(db_index=True, max_length=80)),
                ('chat_id', models.CharField(db_index=True, max_length=80)),
                ('username', models.CharField(blank=True, db_index=True, max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('buy_wait_name', 'Buy: waiting for payer name'), ('buy_wait_last4', 'Buy: waiting for card last4'), ('buy_wait_time', 'Buy: waiting for payment time'), ('buy_wait_tracking', 'Buy: waiting for bank tracking'), ('buy_wait_receipt', 'Buy: waiting for receipt'), ('grant_wait_user', 'Grant: waiting for user'), ('grant_wait_reason', 'Grant: waiting for reason'), ('grant_confirm', 'Grant: confirm')], db_index=True, default='idle', max_length=40)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bot_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_users', to='store.botconfiguration')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='store.customer')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['bot_config', 'provider_user_id'], name='store_botus_bot_con_88993b_idx'), models.Index(fields=['bot_config', 'chat_id'], name='store_botus_bot_con_ebdd7a_idx'), models.Index(fields=['bot_config', 'state', 'last_seen_at'], name='store_botus_bot_con_4fc8c1_idx')],
                'constraints': [models.UniqueConstraint(fields=('bot_config', 'provider_user_id'), name='unique_bot_user_per_config')],
            },
        ),
    ]
