# Generated by Django 6.0.4 on 2026-05-04 18:46

import django.core.validators
from django.db import migrations, models
from django.db.models import Q


def mark_existing_coupon_discounts(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    Order.objects.filter(discount_amount__gt=0).filter(
        Q(discount_code__isnull=False) | ~Q(discount_code_text='')
    ).update(discount_source='manual')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Permanent wholesale discount percentage used when no coupon code is applied.', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_wholesale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_source',
            field=models.CharField(choices=[('none', 'No discount'), ('manual', 'Manual coupon'), ('wholesale', 'Wholesale discount')], db_index=True, default='none', max_length=20),
        ),
        migrations.RunPython(mark_existing_coupon_discounts, migrations.RunPython.noop),
    ]
