# Generated by Django 6.0.4 on 2026-05-04 19:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import store.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botconfiguration',
            options={'ordering': ['provider', 'name'], 'verbose_name': 'bot configuration', 'verbose_name_plural': 'bot configurations'},
        ),
        migrations.AlterModelOptions(
            name='boteventlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'bot event log', 'verbose_name_plural': 'bot event logs'},
        ),
        migrations.AlterModelOptions(
            name='botpendingaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'bot pending action', 'verbose_name_plural': 'bot pending actions'},
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-last_seen_at'], 'verbose_name': 'bot user', 'verbose_name_plural': 'bot users'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='customerreward',
            options={'ordering': ['-earned_at'], 'verbose_name': 'customer reward', 'verbose_name_plural': 'customer rewards'},
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['code'], 'verbose_name': 'discount code', 'verbose_name_plural': 'discount codes'},
        ),
        migrations.AlterModelOptions(
            name='inbound',
            options={'ordering': ['panel__name', 'inbound_id'], 'verbose_name': 'inbound', 'verbose_name_plural': 'inbounds'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['name'], 'verbose_name': 'panel', 'verbose_name_plural': 'panels'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price', 'id'], 'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at'], 'verbose_name': 'referral', 'verbose_name_plural': 'referrals'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
        migrations.AlterModelOptions(
            name='vpnclient',
            options={'ordering': ['-created_at'], 'verbose_name': 'VPN client', 'verbose_name_plural': 'VPN clients'},
        ),
        migrations.AlterModelOptions(
            name='vpnclientusagesnapshot',
            options={'ordering': ['recorded_at'], 'verbose_name': 'VPN client usage snapshot', 'verbose_name_plural': 'VPN client usage snapshots'},
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='admin_user_id',
            field=models.CharField(help_text='Admin chat/user ID that receives notifications.', max_length=80, verbose_name='admin user ID'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='bot_token',
            field=models.CharField(help_text='Bot token from Bale or Telegram.', max_length=255, verbose_name='bot token'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='last error'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='last_report_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last report sent at'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='name',
            field=models.CharField(default='Admin bot', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='notify_new_orders',
            field=models.BooleanField(default=True, verbose_name='notify new orders'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='notify_order_updates',
            field=models.BooleanField(default=True, verbose_name='notify order updates'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='provider',
            field=models.CharField(choices=[('bale', 'Bale'), ('telegram', 'Telegram')], db_index=True, default='bale', max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='report_interval_hours',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='report interval hours'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='send_sales_reports',
            field=models.BooleanField(default=True, verbose_name='send sales reports'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_configurations', to='store.store', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='webhook_secret',
            field=models.CharField(default=store.models.generate_bot_webhook_secret, editable=False, max_length=32, unique=True, verbose_name='webhook secret'),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='bot_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='store.botconfiguration', verbose_name='bot configuration'),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='event_type',
            field=models.CharField(choices=[('new_order', 'New order'), ('order_approved', 'Order approved'), ('order_rejected', 'Order rejected'), ('sales_report', 'Sales report'), ('webhook', 'Webhook'), ('callback', 'Callback'), ('error', 'Error')], db_index=True, max_length=30, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_event_logs', to='store.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='raw payload'),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('sent', 'Sent'), ('received', 'Received'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='action',
            field=models.CharField(choices=[('reject_order', 'Reject order')], max_length=30, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='admin_user_id',
            field=models.CharField(db_index=True, max_length=80, verbose_name='admin user ID'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='bot_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='store.botconfiguration', verbose_name='bot configuration'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_pending_actions', to='store.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resolved at'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='bot_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_users', to='store.botconfiguration', verbose_name='bot configuration'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.CharField(db_index=True, max_length=80, verbose_name='chat ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_users', to='store.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='last seen at'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='provider_user_id',
            field=models.CharField(db_index=True, max_length=80, verbose_name='provider user ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('buy_wait_name', 'Buy: waiting for payer name'), ('buy_wait_last4', 'Buy: waiting for card last4'), ('buy_wait_time', 'Buy: waiting for payment time'), ('buy_wait_tracking', 'Buy: waiting for bank tracking'), ('buy_wait_receipt', 'Buy: waiting for receipt'), ('grant_wait_user', 'Grant: waiting for user'), ('grant_wait_reason', 'Grant: waiting for reason'), ('grant_confirm', 'Grant: confirm')], db_index=True, default='idle', max_length=40, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='state_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='state data'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Permanent wholesale discount percentage used when no coupon code is applied.', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='default discount percent'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='first IP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_wholesale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is wholesale'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='last IP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='last seen at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='public_id',
            field=models.UUIDField(default=store.models.generate_public_id, editable=False, unique=True, verbose_name='public ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, unique=True, verbose_name='referral code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=16, verbose_name='referral code used'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='referred at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='store.customer', verbose_name='referred by'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_agent_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='user agent hash'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='store.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_rewards', to='store.discountcode', verbose_name='discount code'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='earned_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='earned at'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='milestone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='milestone'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_rewards', to='store.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='store.referral', verbose_name='referral'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='reward_type',
            field=models.CharField(choices=[('discount_20', '20% discount coupon'), ('free_1gb_plan', 'Free 1GB plan')], db_index=True, max_length=30, verbose_name='reward type'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='customerreward',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='used at'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to allow this code for every active plan.', related_name='discount_codes', to='store.plan', verbose_name='applicable plans'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=20, verbose_name='discount type'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_usage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum usage'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='used count'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valid until'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='value',
            field=models.PositiveIntegerField(help_text='Percentage value or fixed amount in the order currency.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='config_params',
            field=models.CharField(max_length=500, verbose_name='configuration parameters'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='current_users',
            field=models.PositiveIntegerField(default=0, verbose_name='current users'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='fingerprint',
            field=models.CharField(blank=True, default='chrome', max_length=50, null=True, verbose_name='fingerprint'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='inbound_id',
            field=models.PositiveIntegerField(help_text='Inbound ID in Sanaei/X-UI.', verbose_name='inbound ID'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last synced at'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='max_clients',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum clients'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='network_type',
            field=models.CharField(choices=[('tcp', 'TCP'), ('ws', 'WebSocket'), ('grpc', 'gRPC')], default='tcp', max_length=20, verbose_name='network type'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='store.panel', verbose_name='panel'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='pbk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='public key'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='port',
            field=models.CharField(max_length=10, verbose_name='port'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='protocol',
            field=models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMESS'), ('trojan', 'Trojan')], default='vless', max_length=20, verbose_name='protocol'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='remark',
            field=models.CharField(blank=True, max_length=150, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='security',
            field=models.CharField(choices=[('none', 'None'), ('tls', 'TLS'), ('reality', 'Reality')], default='none', max_length=20, verbose_name='security'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='server_ip',
            field=models.CharField(max_length=100, verbose_name='server IP'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='sid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short ID'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='sni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SNI'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='ws_host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WebSocket host'),
        ),
        migrations.AlterField(
            model_name='inbound',
            name='ws_path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WebSocket path'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bank_tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bank tracking code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='card last four digits'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('TOMAN', 'Toman'), ('IRR', 'Iranian Rial'), ('USD', 'US Dollar')], default='TOMAN', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direct_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='direct link'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.discountcode', verbose_name='discount code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='discount code text'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_source',
            field=models.CharField(choices=[('none', 'No discount'), ('manual', 'Manual coupon'), ('wholesale', 'Wholesale discount')], db_index=True, default='none', max_length=20, verbose_name='discount source'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway_authority',
            field=models.CharField(blank=True, max_length=100, verbose_name='gateway authority'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway_reference_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='gateway reference ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.inbound', verbose_name='inbound'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_tracking_code',
            field=models.CharField(db_index=True, default=store.models.generate_order_tracking, help_text='Public tracking code used by customers and admins to find this order.', max_length=36, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid tracking code.', regex='^([A-Za-z0-9]{8}|[0-9a-fA-F]{32}|[0-9a-fA-F-]{36})$')], verbose_name='order tracking code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='original_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='original amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='payment date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, verbose_name='payment gateway'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('manual_card', 'Manual card-to-card'), ('gateway', 'Online gateway'), ('admin_free', 'Admin free subscription')], db_index=True, default='manual_card', max_length=30, verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='payment receipt image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='payment submitted at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='payment time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(default=store.models.generate_public_id, editable=False, unique=True, verbose_name='public ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of VPN accounts requested in this order.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='rejection reason'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_card_last4',
            field=models.CharField(blank=True, help_text='Last four digits of the payer card.', max_length=4, validators=[django.core.validators.RegexValidator(message='Enter exactly 4 digits.', regex='^\\d{4}$')], verbose_name='sender card last 4 digits'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender_card_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='sender card name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('pending_verification', 'Pending verification'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', help_text='Operational lifecycle status of the order.', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.store', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='subscription link'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(default='admin', max_length=100, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Manual or SMS payment verification status.', max_length=20, verbose_name='verification status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verified at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to=settings.AUTH_USER_MODEL, verbose_name='verified by'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last sync at'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='password',
            field=models.CharField(max_length=100, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='store.store', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='url',
            field=models.URLField(help_text='Full panel URL without trailing slash.', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='username',
            field=models.CharField(max_length=100, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('TOMAN', 'Toman'), ('IRR', 'Iranian Rial'), ('USD', 'US Dollar')], default='TOMAN', max_length=10, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='device_limit',
            field=models.PositiveIntegerField(default=2, verbose_name='device limit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Plan duration in days.', verbose_name='duration in days'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Hide internal reward plans from the public plan selector when disabled.', verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(help_text='Plan price in the selected currency.', verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='store.store', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='volume_gb',
            field=models.DecimalField(decimal_places=3, help_text='Traffic limit in GB. Use decimal values for small plans, e.g. 0.1 for 100 MB.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='volume in GB'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='first_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_conversions', to='store.order', verbose_name='first order'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='purchased at'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(db_index=True, max_length=16, verbose_name='referral code'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to='store.customer', verbose_name='referred customer'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='store.customer', verbose_name='referrer'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='store',
            name='bale_support',
            field=models.CharField(blank=True, help_text='Bale support username, @username, or full ble.ir link.', max_length=200, null=True, verbose_name='Bale support'),
        ),
        migrations.AlterField(
            model_name='store',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='card_number',
            field=models.CharField(help_text='Manual card-to-card destination card number, without spaces.', max_length=16, verbose_name='card number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='card_owner',
            field=models.CharField(max_length=100, verbose_name='card owner'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='store',
            name='english_name',
            field=models.CharField(default='VPN Store', max_length=100, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='hero_text',
            field=models.TextField(default='Buy a VPN plan and receive your configuration after payment verification.', verbose_name='hero text'),
        ),
        migrations.AlterField(
            model_name='store',
            name='hero_title',
            field=models.CharField(default='Fast and secure VPN access', max_length=200, verbose_name='hero title'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='VPN Store', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='Sheba number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='store',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='support email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram_channel',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram channel'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telegram_support',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram support'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='activated at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='device_limit',
            field=models.PositiveIntegerField(default=2, verbose_name='device limit'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='direct_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='direct link'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='disabled at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, verbose_name='duration days'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_clients', to='store.inbound', verbose_name='inbound'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='last_online_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last online at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last synced at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_clients', to='store.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_clients', to='store.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='public_id',
            field=models.UUIDField(default=store.models.generate_public_id, editable=False, unique=True, verbose_name='public ID'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('error', 'Error')], db_index=True, default='created', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vpn_clients', to='store.store', verbose_name='store'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='sub_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='subscription ID'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='sub_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='subscription link'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='traffic_limit_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='traffic limit bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='used_download_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='used download bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='used_traffic_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='used traffic bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='used_upload_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='used upload bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='username',
            field=models.CharField(db_index=True, max_length=150, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='xui_email',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='X-UI email'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='xui_raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='X-UI raw data'),
        ),
        migrations.AlterField(
            model_name='vpnclientusagesnapshot',
            name='raw',
            field=models.JSONField(blank=True, default=dict, verbose_name='raw data'),
        ),
        migrations.AlterField(
            model_name='vpnclientusagesnapshot',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='recorded at'),
        ),
        migrations.AlterField(
            model_name='vpnclientusagesnapshot',
            name='remaining_traffic_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='remaining traffic bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclientusagesnapshot',
            name='total_traffic_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='total traffic bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclientusagesnapshot',
            name='used_download_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='used download bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclientusagesnapshot',
            name='used_traffic_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='used traffic bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclientusagesnapshot',
            name='used_upload_bytes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='used upload bytes'),
        ),
        migrations.AlterField(
            model_name='vpnclientusagesnapshot',
            name='vpn_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='store.vpnclient', verbose_name='VPN client'),
        ),
    ]
