# Generated by Django 6.0.4 on 2026-05-06 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_store_receipt_image_only_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('system', 'System')], db_index=True, max_length=20, verbose_name='sender type')),
                ('body', models.TextField(verbose_name='body')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'support message',
                'verbose_name_plural': 'support messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='boteventlog',
            name='event_type',
            field=models.CharField(choices=[('new_order', 'New order'), ('order_approved', 'Order approved'), ('order_rejected', 'Order rejected'), ('support_message', 'Support message'), ('support_reply', 'Support reply'), ('sales_report', 'Sales report'), ('webhook', 'Webhook'), ('callback', 'Callback'), ('error', 'Error')], db_index=True, max_length=30, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='action',
            field=models.CharField(choices=[('reject_order', 'Reject order'), ('support_reply', 'Support reply')], max_length=30, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='botpendingaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_pending_actions', to='store.order', verbose_name='order'),
        ),
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('subject', models.CharField(default='Support chat', max_length=150, verbose_name='subject')),
                ('contact_value', models.CharField(blank=True, help_text='Customer phone number, Telegram username, or Telegram ID for follow-up.', max_length=120, verbose_name='phone number or Telegram ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_admin', 'Waiting for admin'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=30, verbose_name='status')),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True, verbose_name='last customer message at')),
                ('last_admin_message_at', models.DateTimeField(blank=True, null=True, verbose_name='last admin message at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to='store.customer', verbose_name='customer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to='store.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'support conversation',
                'verbose_name_plural': 'support conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='botpendingaction',
            name='support_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_pending_actions', to='store.supportconversation', verbose_name='support conversation'),
        ),
        migrations.AddIndex(
            model_name='botpendingaction',
            index=models.Index(fields=['support_conversation', 'status'], name='store_botpe_support_fccbe6_idx'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='bot_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='store.botconfiguration', verbose_name='bot configuration'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.supportconversation', verbose_name='support conversation'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='store.customer', verbose_name='customer'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['customer', 'status', 'updated_at'], name='store_suppo_custome_da110b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['store', 'status', 'updated_at'], name='store_suppo_store_i_fbad78_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='store_suppo_convers_2597c4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender_type', 'created_at'], name='store_suppo_sender__8b4ae4_idx'),
        ),
    ]
