# Generated by Django 6.0.4 on 2026-06-04 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_botuser_profile_phone_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sales_mode',
            field=models.CharField(choices=[('tunnel', 'Tunnel'), ('operator_based', 'Operator based')], db_index=True, default='tunnel', help_text='Tunnel shows plans directly; operator based asks customers to choose an operator first.', max_length=30, verbose_name='sales mode'),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='store.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'operator',
                'verbose_name_plural': 'operators',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Selected internet operator for operator-based sales mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.operator', verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='plan',
            name='operators',
            field=models.ManyToManyField(blank=True, help_text='Operators that can buy this plan when operator-based sales mode is enabled.', related_name='plans', to='store.operator', verbose_name='operators'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['operator', 'status', 'created_at'], name='store_order_operato_34fb05_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['store', 'is_active', 'sort_order'], name='store_opera_store_i_91a4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='operator',
            index=models.Index(fields=['is_active', 'sort_order'], name='store_opera_is_acti_464f2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='operator',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('store', 'slug'), name='unique_operator_slug_per_store'),
        ),
    ]
