# Generated by Django 6.0.4 on 2026-06-04 11:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


def backfill_blank_customer_referral_codes(apps, schema_editor):
    Customer = apps.get_model('store', 'Customer')
    used_codes = set(
        Customer.objects.exclude(referral_code__isnull=True)
        .exclude(referral_code='')
        .values_list('referral_code', flat=True)
    )
    blank_customers = Customer.objects.filter(
        models.Q(referral_code__isnull=True) | models.Q(referral_code='')
    )
    for customer in blank_customers.iterator():
        for _ in range(20):
            code = f"RF{uuid.uuid4().hex[:8].upper()}"
            if code not in used_codes:
                break
        else:
            code = f"RF{uuid.uuid4().hex[:10].upper()}"
        used_codes.add(code)
        Customer.objects.filter(pk=customer.pk).update(referral_code=code)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_backfill_orphan_inbound_panels'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='referral_min_order_required',
            field=models.BooleanField(default=True, help_text="Only the invited customer's first successful order can create the referral reward.", verbose_name='referral minimum order required'),
        ),
        migrations.AddField(
            model_name='store',
            name='referral_reward_gb',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.000'), help_text='Gift traffic awarded to the inviter after an eligible invited purchase.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='referral reward GB'),
        ),
        migrations.AddField(
            model_name='store',
            name='referral_system_enabled',
            field=models.BooleanField(default=True, help_text='When disabled, referral codes remain visible but new GB rewards are not created.', verbose_name='referral system enabled'),
        ),
        migrations.RunPython(backfill_blank_customer_referral_codes, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ReferralRewardLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('reward_gb', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='reward GB')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('available_at', models.DateTimeField(blank=True, null=True, verbose_name='available at')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='redeemed at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_gb_rewards', to='store.customer', verbose_name='invited customer')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_gb_rewards', to='store.customer', verbose_name='inviter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_reward_ledgers', to='store.order', verbose_name='order')),
                ('redeemed_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_referral_rewards', to='store.vpnclient', verbose_name='redeemed VPN config')),
            ],
            options={
                'verbose_name': 'referral reward ledger',
                'verbose_name_plural': 'referral reward ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inviter', 'status', 'created_at'], name='store_refer_inviter_703981_idx'), models.Index(fields=['invited', 'status'], name='store_refer_invited_63c521_idx'), models.Index(fields=['order', 'status'], name='store_refer_order_i_3e7987_idx')],
                'constraints': [models.UniqueConstraint(fields=('invited',), name='unique_referral_gb_reward_per_invited_customer'), models.CheckConstraint(condition=models.Q(('inviter', models.F('invited')), _negated=True), name='referral_gb_reward_no_self_invite')],
            },
        ),
    ]
