# Generated by Django 6.0.4 on 2026-06-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_store_referral_min_order_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalyticsReport',
            fields=[
            ],
            options={
                'verbose_name': 'customer analytics report',
                'verbose_name_plural': 'customer analytics reports',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.customer',),
        ),
        migrations.AddField(
            model_name='store',
            name='analytics_enabled',
            field=models.BooleanField(default=True, help_text='Enable customer analytics reports in admin and admin bots.', verbose_name='analytics enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='good_customer_min_total_amount',
            field=models.PositiveIntegerField(default=500000, help_text='Minimum successful purchase amount used to tag good customers.', verbose_name='good customer minimum total amount'),
        ),
        migrations.AddField(
            model_name='store',
            name='inactive_customer_days',
            field=models.PositiveIntegerField(default=30, help_text='Customers with older successful purchases and no recent purchase are tagged inactive.', verbose_name='inactive customer days'),
        ),
        migrations.AddField(
            model_name='store',
            name='loyal_customer_min_orders_30d',
            field=models.PositiveIntegerField(default=2, help_text='Minimum successful orders in the last 30 days used to tag loyal customers.', verbose_name='loyal customer minimum orders in 30 days'),
        ),
        migrations.AddField(
            model_name='store',
            name='top_customers_limit',
            field=models.PositiveIntegerField(default=10, help_text='Number of customers included in top buyer and top referrer segments.', verbose_name='top customers limit'),
        ),
    ]
