# Generated by Django 6.0.4 on 2026-06-04 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_customeranalyticsreport_store_analytics_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='broadcast_enabled',
            field=models.BooleanField(default=True, help_text='Allow admins to send targeted broadcast campaigns.', verbose_name='broadcast enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='broadcast_max_recipients_per_campaign',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum customers resolved for a single broadcast campaign.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='broadcast max recipients per campaign'),
        ),
        migrations.AddField(
            model_name='store',
            name='broadcast_rate_limit_per_second',
            field=models.PositiveIntegerField(default=5, help_text='Maximum customer broadcast messages sent per second.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='broadcast rate limit per second'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('profile_wait_phone', 'Profile: waiting for phone'), ('buy_wait_custom_volume', 'Buy: waiting for custom volume'), ('buy_wait_quantity', 'Buy: waiting for quantity'), ('buy_wait_name', 'Buy: waiting for payer name'), ('buy_wait_last4', 'Buy: waiting for card last4'), ('buy_wait_time', 'Buy: waiting for payment time'), ('buy_wait_tracking', 'Buy: waiting for bank tracking'), ('buy_wait_receipt', 'Buy: waiting for receipt'), ('grant_wait_user', 'Grant: waiting for user'), ('grant_wait_reason', 'Grant: waiting for reason'), ('grant_confirm', 'Grant: confirm'), ('broadcast_wait_text', 'Broadcast: waiting for text'), ('broadcast_confirm', 'Broadcast: confirm')], db_index=True, default='idle', max_length=40, verbose_name='state'),
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('title', models.CharField(max_length=180, verbose_name='title')),
                ('message_text', models.TextField(verbose_name='message text')),
                ('audience_type', models.CharField(choices=[('all', 'All'), ('active_customers', 'Active customers'), ('customers_with_active_config', 'Customers with active config'), ('customers_without_order', 'Customers without order'), ('loyal', 'Loyal'), ('good', 'Good'), ('top_buyer', 'Top buyer'), ('top_referrer', 'Top referrer'), ('inactive', 'Inactive'), ('no_order', 'No order')], db_index=True, default='all', max_length=40, verbose_name='audience type')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('all_available', 'All available')], db_index=True, default='telegram', max_length=30, verbose_name='channel')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total recipients')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='success count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='failed count')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_messages', to='store.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'broadcast message',
                'verbose_name_plural': 'broadcast messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('all_available', 'All available')], db_index=True, max_length=30, verbose_name='channel')),
                ('target_identifier', models.CharField(blank=True, max_length=120, verbose_name='target identifier')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='store.broadcastmessage', verbose_name='campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_recipients', to='store.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'broadcast recipient',
                'verbose_name_plural': 'broadcast recipients',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['audience_type', 'status'], name='store_broad_audienc_e92269_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['channel', 'status'], name='store_broad_channel_bbfc35_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['scheduled_at', 'status'], name='store_broad_schedul_cdfeae_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['campaign', 'status'], name='store_broad_campaig_16604f_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['customer', 'channel'], name='store_broad_custome_a3617d_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['channel', 'status'], name='store_broad_channel_8af8c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='broadcastrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'customer', 'channel'), name='unique_broadcast_recipient_per_channel'),
        ),
    ]
