# Generated by Django 6.0.4 on 2026-06-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_store_broadcast_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='force_telegram_channel_join',
            field=models.BooleanField(default=False, help_text='Require Telegram users to join the configured channel before using customer bot actions.', verbose_name='force Telegram channel join'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='telegram_join_check_message',
            field=models.TextField(blank=True, default='برای استفاده از ربات ابتدا عضو کانال شوید.', verbose_name='Telegram join check message'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='telegram_required_channel_id',
            field=models.CharField(blank=True, help_text='Numeric channel ID, for example -1001234567890.', max_length=120, verbose_name='Telegram required channel ID'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='telegram_required_channel_invite_link',
            field=models.URLField(blank=True, help_text='Public or private invite link shown to users.', max_length=255, verbose_name='Telegram required channel invite link'),
        ),
        migrations.AddField(
            model_name='botconfiguration',
            name='telegram_required_channel_username',
            field=models.CharField(blank=True, help_text='Channel username with or without @.', max_length=100, verbose_name='Telegram required channel username'),
        ),
    ]
