# Generated by Django 6.0.4 on 2026-06-05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0033_botconfiguration_force_telegram_channel_join_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="proxy_url",
            field=models.URLField(
                blank=True,
                help_text="Optional HTTP proxy URL for this panel, e.g. http://proxy-host:port.",
                max_length=500,
                null=True,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                verbose_name="HTTP proxy URL",
            ),
        ),
    ]
