# Generated by Django 6.0.4 on 2026-06-05 22:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_order_admin_notification_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='free_trial_cooldown_days',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='free trial cooldown days'),
        ),
        migrations.AddField(
            model_name='store',
            name='free_trial_duration_hours',
            field=models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)], verbose_name='free trial duration hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='free_trial_enabled',
            field=models.BooleanField(default=False, help_text='Allow bot users to receive one free test configuration per cooldown window.', verbose_name='free trial enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='free_trial_inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_trial_stores', to='store.inbound', verbose_name='free trial inbound'),
        ),
        migrations.AddField(
            model_name='store',
            name='free_trial_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_trial_stores', to='store.panel', verbose_name='free trial panel'),
        ),
        migrations.AddField(
            model_name='store',
            name='free_trial_traffic_gb',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='free trial traffic GB'),
        ),
        migrations.CreateModel(
            name='FreeTrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('telegram_user_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Telegram user ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20, verbose_name='status')),
                ('traffic_gb', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='traffic GB')),
                ('duration_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='duration hours')),
                ('config_link', models.TextField(blank=True, verbose_name='config link')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_trial_requests', to='store.customer', verbose_name='customer')),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_trial_requests', to='store.inbound', verbose_name='inbound')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_trial_requests', to='store.panel', verbose_name='panel')),
                ('vpn_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_trial_requests', to='store.vpnclient', verbose_name='VPN client')),
            ],
            options={
                'verbose_name': 'free trial request',
                'verbose_name_plural': 'free trial requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='store_freet_custome_bc7456_idx'), models.Index(fields=['telegram_user_id', 'created_at'], name='store_freet_telegra_5b66ae_idx'), models.Index(fields=['status', 'created_at'], name='store_freet_status_293a15_idx')],
            },
        ),
    ]
