# Generated by Django 6.0.4 on 2026-06-06 00:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_store_free_trial_cooldown_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrewardledger',
            name='applied_duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Duration actually applied when this package was redeemed.', verbose_name='applied duration days'),
        ),
        migrations.AddField(
            model_name='referralrewardledger',
            name='applied_traffic_gb',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Traffic actually applied when this package was redeemed.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='applied traffic GB'),
        ),
        migrations.AddField(
            model_name='referralrewardledger',
            name='reward_duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Duration amount for this gift package.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='reward duration days'),
        ),
        migrations.AddField(
            model_name='store',
            name='referral_reward_duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Gift-package duration awarded to the inviter after an eligible invited purchase.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='referral reward duration days'),
        ),
        migrations.AlterField(
            model_name='referralrewardledger',
            name='reward_gb',
            field=models.DecimalField(decimal_places=3, help_text='Traffic amount for this gift package. Kept as reward_gb for legacy compatibility.', max_digits=8, verbose_name='reward traffic GB'),
        ),
        migrations.AlterField(
            model_name='store',
            name='referral_reward_gb',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.000'), help_text='Gift-package traffic awarded to the inviter after an eligible invited purchase.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='referral reward traffic GB'),
        ),
    ]
