# Generated by Django 6.0.4 on 2026-06-06 13:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import store.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_referralrewardledger_applied_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='low_traffic_gb_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.000'), help_text='Send a reminder when remaining traffic GB is at or below this value.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='low traffic GB threshold'),
        ),
        migrations.AddField(
            model_name='store',
            name='low_traffic_percent_threshold',
            field=models.PositiveIntegerField(default=20, help_text='Send a reminder when remaining traffic percent is at or below this value.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='low traffic percent threshold'),
        ),
        migrations.AddField(
            model_name='store',
            name='low_traffic_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Send Telegram reminders when remaining traffic is below the configured thresholds.', verbose_name='low traffic reminders enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='reminder_cooldown_hours',
            field=models.PositiveIntegerField(default=24, help_text='Minimum hours between retryable reminders for the same VPN client.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='reminder cooldown hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='reminder_days_after_expiry',
            field=models.JSONField(blank=True, default=store.models.default_reminder_days_after_expiry, help_text='Integer day offsets after expiry, for example [1, 3].', verbose_name='reminder days after expiry'),
        ),
        migrations.AddField(
            model_name='store',
            name='reminder_days_before_expiry',
            field=models.JSONField(blank=True, default=store.models.default_reminder_days_before_expiry, help_text='Integer day offsets before expiry, for example [3, 1, 0].', verbose_name='reminder days before expiry'),
        ),
        migrations.AddField(
            model_name='store',
            name='reminder_max_per_client_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Maximum sent reminder messages per VPN client per calendar day.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='reminder max per client per day'),
        ),
        migrations.AddField(
            model_name='store',
            name='renewal_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Send Telegram reminders before and after VPN client expiry.', verbose_name='renewal reminders enabled'),
        ),
        migrations.CreateModel(
            name='VPNClientReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('reminder_type', models.CharField(choices=[('expiry_before', 'Expiry before'), ('expiry_today', 'Expiry today'), ('expiry_after', 'Expiry after'), ('low_traffic', 'Low traffic')], db_index=True, max_length=30, verbose_name='reminder type')),
                ('trigger_key', models.CharField(db_index=True, max_length=80, verbose_name='trigger key')),
                ('trigger_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='trigger date')),
                ('sent_to_telegram_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='sent to Telegram ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='skipped', max_length=20, verbose_name='status')),
                ('message_text', models.TextField(blank=True, verbose_name='message text')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_reminder_logs', to='store.customer', verbose_name='customer')),
                ('vpn_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='store.vpnclient', verbose_name='VPN client')),
            ],
            options={
                'verbose_name': 'VPN client reminder log',
                'verbose_name_plural': 'VPN client reminder logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='store_vpncl_custome_c89ec9_idx'), models.Index(fields=['vpn_client', 'reminder_type', 'trigger_key'], name='store_vpncl_vpn_cli_89ee50_idx'), models.Index(fields=['status', 'trigger_date'], name='store_vpncl_status_9a8ff1_idx')],
                'constraints': [models.UniqueConstraint(fields=('vpn_client', 'reminder_type', 'trigger_key', 'trigger_date'), name='unique_vpn_client_reminder_per_trigger_date')],
            },
        ),
    ]
