# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0038_store_low_traffic_gb_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="renewal_reminders_start_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "اگر تنظیم شود، یادآوری فقط برای سرویس‌هایی ارسال می‌شود که بعد از این زمان ساخته شده‌اند. "
                    "برای نادیده گرفتن دیتای قدیمی استفاده می‌شود."
                ),
                null=True,
                verbose_name="renewal reminders start at",
            ),
        ),
    ]
