# Generated by Django 6.0.4 on 2026-06-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_store_renewal_reminders_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiguration',
            name='telegram_bot_username',
            field=models.CharField(blank=True, help_text='نام کاربری ربات بدون @، برای ساخت لینک دعوت و start parameter استفاده می\u200cشود.', max_length=64, verbose_name='Telegram bot username'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_sms_time_zone',
            field=models.CharField(blank=True, default='Asia/Tehran', help_text='Time zone used when parsing bank SMS dates. Leave blank to use the legacy settings fallback.', max_length=64, verbose_name='payment SMS time zone'),
        ),
        migrations.AddField(
            model_name='store',
            name='smsforwarder_webhook_token_hash',
            field=models.CharField(blank=True, editable=False, help_text='Hashed SMSForwarder webhook token. Set or rotate it from the admin write-only token field.', max_length=255, verbose_name='SMSForwarder webhook token hash'),
        ),
        migrations.AddField(
            model_name='store',
            name='smsforwarder_webhook_token_hint',
            field=models.CharField(blank=True, editable=False, help_text='Last characters of the configured webhook token, used only as an admin hint.', max_length=16, verbose_name='SMSForwarder webhook token hint'),
        ),
    ]
