# Generated by Django 6.0.4 on 2026-06-06 22:24

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_botconfiguration_telegram_bot_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='daily_admin_report_enabled',
            field=models.BooleanField(default=True, help_text='Send the daily Telegram admin operations report for this store.', verbose_name='daily admin report enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='daily_admin_report_include_errors',
            field=models.BooleanField(default=True, verbose_name='daily admin report include errors'),
        ),
        migrations.AddField(
            model_name='store',
            name='daily_admin_report_include_financials',
            field=models.BooleanField(default=True, verbose_name='daily admin report include financials'),
        ),
        migrations.AddField(
            model_name='store',
            name='daily_admin_report_include_panel_health',
            field=models.BooleanField(default=True, verbose_name='daily admin report include panel health'),
        ),
        migrations.AddField(
            model_name='store',
            name='daily_admin_report_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Intended local send time. Scheduling is handled by cron/systemd.', verbose_name='daily admin report time'),
        ),
        migrations.AddField(
            model_name='store',
            name='daily_admin_report_timezone',
            field=models.CharField(blank=True, default='Asia/Tehran', help_text='IANA timezone used to calculate the daily report period.', max_length=64, verbose_name='daily admin report timezone'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_monitor_alert_cooldown_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='panel monitor alert cooldown minutes'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_monitor_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Send Telegram admin alerts when panel health changes or cooldown reminders are due.', verbose_name='panel monitor alerts enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_monitor_check_timeout_seconds',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='panel monitor check timeout seconds'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_monitor_enabled',
            field=models.BooleanField(default=True, help_text='Run operational health checks for active X-UI/Sanaei panels.', verbose_name='panel monitor enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_monitor_max_log_age_days',
            field=models.PositiveIntegerField(default=30, help_text='Panel health check logs older than this value can be removed by the cleanup command.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='panel monitor max log age days'),
        ),
        migrations.CreateModel(
            name='DailyAdminReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, verbose_name='report date')),
                ('period_start', models.DateTimeField(verbose_name='period start')),
                ('period_end', models.DateTimeField(verbose_name='period end')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, max_length=20, verbose_name='status')),
                ('sent_to_count', models.PositiveIntegerField(default=0, verbose_name='sent to count')),
                ('message_text', models.TextField(blank=True, verbose_name='message text')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_admin_report_logs', to='store.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'daily admin report log',
                'verbose_name_plural': 'daily admin report logs',
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['store', 'report_date'], name='store_daily_store_i_47cff9_idx'), models.Index(fields=['status', 'created_at'], name='store_daily_status_7be27f_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'report_date'), name='unique_daily_admin_report_per_store_date')],
            },
        ),
        migrations.CreateModel(
            name='PanelHealthCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error'), ('disabled', 'Disabled')], db_index=True, max_length=20, verbose_name='status')),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='checked at')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='response time ms')),
                ('login_ok', models.BooleanField(blank=True, null=True, verbose_name='login OK')),
                ('inbounds_checked', models.PositiveIntegerField(default=0, verbose_name='inbounds checked')),
                ('inbounds_ok', models.PositiveIntegerField(default=0, verbose_name='inbounds OK')),
                ('inbounds_warning', models.PositiveIntegerField(default=0, verbose_name='inbounds warning')),
                ('inbounds_error', models.PositiveIntegerField(default=0, verbose_name='inbounds error')),
                ('error_code', models.CharField(blank=True, max_length=80, verbose_name='error code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('alert_sent', models.BooleanField(default=False, verbose_name='alert sent')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_check_logs', to='store.panel', verbose_name='panel')),
            ],
            options={
                'verbose_name': 'panel health check log',
                'verbose_name_plural': 'panel health check logs',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['panel', 'checked_at'], name='store_panel_panel_i_439e26_idx'), models.Index(fields=['status', 'checked_at'], name='store_panel_status_cad758_idx'), models.Index(fields=['alert_sent', 'checked_at'], name='store_panel_alert_s_d65a44_idx')],
            },
        ),
        migrations.CreateModel(
            name='PanelHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error'), ('disabled', 'Disabled')], db_index=True, default='unknown', max_length=20, verbose_name='status')),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last checked at')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='last OK at')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='last error at')),
                ('last_alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='last alert sent at')),
                ('last_recovery_alert_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='last recovery alert sent at')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='consecutive failures')),
                ('consecutive_successes', models.PositiveIntegerField(default=0, verbose_name='consecutive successes')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='response time ms')),
                ('error_code', models.CharField(blank=True, max_length=80, verbose_name='error code')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('panel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_status', to='store.panel', verbose_name='panel')),
            ],
            options={
                'verbose_name': 'panel health status',
                'verbose_name_plural': 'panel health statuses',
                'ordering': ['panel__name'],
                'indexes': [models.Index(fields=['status', 'last_checked_at'], name='store_panel_status_77a17e_idx')],
            },
        ),
    ]
