# Generated by Django 6.0.4 on 2026-06-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_store_daily_admin_report_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='available_for_new_orders',
            field=models.BooleanField(db_index=True, default=True, help_text='اگر غیرفعال باشد، این inbound برای فروش جدید، تست رایگان یا ساخت کانفیگ جدید انتخاب نمی\u200cشود.', verbose_name='available for new orders'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='health_monitor_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='اگر غیرفعال باشد، سلامت پنل این inbound را بررسی نمی\u200cکند؛ مناسب inboundهای legacy.', verbose_name='health monitor enabled'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='legacy_note',
            field=models.TextField(blank=True, help_text='توضیح ادمین برای inboundهای قدیمی که برای سفارش\u200cها/کلاینت\u200cهای قبلی نگه داشته شده\u200cاند.', verbose_name='legacy note'),
        ),
        migrations.AddIndex(
            model_name='inbound',
            index=models.Index(fields=['panel', 'is_active', 'available_for_new_orders'], name='store_inbou_panel_i_9e556c_idx'),
        ),
        migrations.AddIndex(
            model_name='inbound',
            index=models.Index(fields=['panel', 'is_active', 'health_monitor_enabled'], name='store_inbou_panel_i_b9cabf_idx'),
        ),
    ]
