# Generated by Django 6.0.4 on 2026-06-07 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_inbound_available_for_new_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allow_global_inbound_fallback',
            field=models.BooleanField(default=True, help_text='اگر route explicit برای پلن پیدا نشد، اجازه استفاده از الگوریتم عمومی انتخاب inbound را می\u200cدهد.', verbose_name='allow global inbound fallback'),
        ),
        migrations.AddField(
            model_name='store',
            name='plan_inbound_routing_enabled',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، فروش هر پلن از routeهای explicit همان پلن/اپراتور به inbound انجام می\u200cشود.', verbose_name='plan inbound routing enabled'),
        ),
        migrations.CreateModel(
            name='PlanInboundRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='عدد کمتر یعنی اولویت بالاتر.', verbose_name='priority')),
                ('weight', models.PositiveIntegerField(default=1, help_text='برای تعادل فروش آینده نگه داشته شده است.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='weight')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('inbound', models.ForeignKey(help_text='Inbound مقصد برای ساخت کانفیگ\u200cهای جدید این پلن.', on_delete=django.db.models.deletion.PROTECT, related_name='plan_routes', to='store.inbound', verbose_name='inbound')),
                ('operator', models.ForeignKey(blank=True, help_text='اگر خالی باشد route عمومی پلن است؛ اگر مقدار داشته باشد فقط برای همان اپراتور استفاده می\u200cشود.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_inbound_routes', to='store.operator', verbose_name='operator')),
                ('plan', models.ForeignKey(help_text='پلنی که فروش آن باید از inbound مشخص انجام شود.', on_delete=django.db.models.deletion.CASCADE, related_name='inbound_routes', to='store.plan', verbose_name='plan')),
                ('store', models.ForeignKey(blank=True, help_text='برای پلن\u200cهای مشترک بین فروشگاه\u200cها می\u200cتوان route را به یک فروشگاه خاص محدود کرد.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_inbound_routes', to='store.store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'plan inbound route',
                'verbose_name_plural': 'plan inbound routes',
                'ordering': ['plan', 'operator', 'priority', 'id'],
                'indexes': [models.Index(fields=['store', 'is_active', 'priority'], name='store_plani_store_i_00b42d_idx'), models.Index(fields=['plan', 'operator', 'is_active', 'priority'], name='store_plani_plan_id_229b8f_idx'), models.Index(fields=['inbound', 'is_active'], name='store_plani_inbound_8d16bf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('operator__isnull', False)), fields=('plan', 'operator', 'inbound'), name='unique_plan_operator_inbound_route'), models.UniqueConstraint(condition=models.Q(('operator__isnull', True)), fields=('plan', 'inbound'), name='unique_plan_default_inbound_route')],
            },
        ),
    ]
