# Generated by Django 6.0.4 on 2026-06-07 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_store_allow_global_inbound_fallback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNClientActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], db_index=True, max_length=20, verbose_name='actor type')),
                ('actor_telegram_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='actor Telegram ID')),
                ('action', models.CharField(choices=[('user_delete', 'User delete'), ('admin_delete', 'Admin delete'), ('admin_update_traffic', 'Admin update traffic'), ('admin_update_expiry', 'Admin update expiry'), ('admin_update_traffic_and_expiry', 'Admin update traffic and expiry'), ('admin_refresh_link', 'Admin refresh link')], db_index=True, max_length=50, verbose_name='action')),
                ('xui_identifier_masked', models.CharField(blank=True, max_length=120, verbose_name='masked X-UI identifier')),
                ('old_total_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='old total bytes')),
                ('new_total_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='new total bytes')),
                ('old_expiry_time', models.DateTimeField(blank=True, null=True, verbose_name='old expiry time')),
                ('new_expiry_time', models.DateTimeField(blank=True, null=True, verbose_name='new expiry time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'VPN client action log',
                'verbose_name_plural': 'VPN client action logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='delete_reason',
            field=models.TextField(blank=True, verbose_name='delete reason'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='deleted_by_admin_telegram_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='deleted by admin Telegram ID'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='deleted_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_vpn_clients', to='store.customer', verbose_name='deleted by customer'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='remote_deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='remote deleted at'),
        ),
        migrations.AlterField(
            model_name='vpnclient',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('deleted', 'Deleted'), ('error', 'Error')], db_index=True, default='created', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='vpnclient',
            index=models.Index(fields=['deleted_at'], name='store_vpncl_deleted_6d886a_idx'),
        ),
        migrations.AddField(
            model_name='vpnclientactionlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_client_action_logs', to='store.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='vpnclientactionlog',
            name='inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_client_action_logs', to='store.inbound', verbose_name='inbound'),
        ),
        migrations.AddField(
            model_name='vpnclientactionlog',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_client_action_logs', to='store.panel', verbose_name='panel'),
        ),
        migrations.AddField(
            model_name='vpnclientactionlog',
            name='vpn_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='store.vpnclient', verbose_name='VPN client'),
        ),
        migrations.AddIndex(
            model_name='vpnclientactionlog',
            index=models.Index(fields=['vpn_client', 'created_at'], name='store_vpncl_vpn_cli_70687f_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnclientactionlog',
            index=models.Index(fields=['customer', 'created_at'], name='store_vpncl_custome_cd4ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnclientactionlog',
            index=models.Index(fields=['action', 'status', 'created_at'], name='store_vpncl_action_df9284_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnclientactionlog',
            index=models.Index(fields=['actor_type', 'actor_telegram_id'], name='store_vpncl_actor_t_f7c18c_idx'),
        ),
    ]
