# Generated by Django 6.0.4 on 2026-06-10 18:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_vpnclientactionlog_vpnclient_delete_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='panel_usage_active_user_method',
            field=models.CharField(choices=[('traffic_delta', 'Traffic delta'), ('online_api', 'Online API'), ('mixed', 'Mixed')], default='mixed', help_text='How daily active panel users are counted from snapshots.', max_length=20, verbose_name='panel usage active user method'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_usage_report_enabled',
            field=models.BooleanField(default=True, help_text='Include panel usage deltas and active users in the daily admin report.', verbose_name='panel usage report enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_usage_snapshot_retention_days',
            field=models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(1)], verbose_name='panel usage snapshot retention days'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_usage_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Collect periodic X-UI/Sanaei usage snapshots for active panels.', verbose_name='panel usage tracking enabled'),
        ),
        migrations.CreateModel(
            name='PanelClientUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, verbose_name='captured at')),
                ('client_identifier_hash', models.CharField(db_index=True, max_length=128, verbose_name='client identifier hash')),
                ('client_identifier_masked', models.CharField(blank=True, max_length=128, verbose_name='client identifier masked')),
                ('email_masked', models.CharField(blank=True, max_length=128, verbose_name='email masked')),
                ('upload_bytes', models.BigIntegerField(default=0, verbose_name='upload bytes')),
                ('download_bytes', models.BigIntegerField(default=0, verbose_name='download bytes')),
                ('used_bytes', models.BigIntegerField(default=0, verbose_name='used bytes')),
                ('total_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='total bytes')),
                ('expiry_time', models.DateTimeField(blank=True, null=True, verbose_name='expiry time')),
                ('enabled', models.BooleanField(blank=True, null=True, verbose_name='enabled')),
                ('online', models.BooleanField(blank=True, null=True, verbose_name='online')),
                ('source', models.CharField(blank=True, max_length=80, verbose_name='source')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('inbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_usage_snapshots', to='store.inbound', verbose_name='inbound')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_usage_snapshots', to='store.panel', verbose_name='panel')),
            ],
            options={
                'verbose_name': 'panel client usage snapshot',
                'verbose_name_plural': 'panel client usage snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['panel', 'captured_at'], name='store_panel_panel_i_90e27b_idx'), models.Index(fields=['client_identifier_hash', 'captured_at'], name='store_panel_client__8d17f5_idx'), models.Index(fields=['inbound', 'captured_at'], name='store_panel_inbound_2b841a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PanelDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(db_index=True, verbose_name='usage date')),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=64, verbose_name='timezone')),
                ('upload_bytes', models.BigIntegerField(default=0, verbose_name='upload bytes')),
                ('download_bytes', models.BigIntegerField(default=0, verbose_name='download bytes')),
                ('used_bytes', models.BigIntegerField(default=0, verbose_name='used bytes')),
                ('active_users_count', models.PositiveIntegerField(default=0, verbose_name='active users count')),
                ('online_users_count', models.PositiveIntegerField(default=0, verbose_name='online users count')),
                ('clients_count_start', models.PositiveIntegerField(default=0, verbose_name='clients count start')),
                ('clients_count_end', models.PositiveIntegerField(default=0, verbose_name='clients count end')),
                ('snapshot_start_at', models.DateTimeField(blank=True, null=True, verbose_name='snapshot start at')),
                ('snapshot_end_at', models.DateTimeField(blank=True, null=True, verbose_name='snapshot end at')),
                ('data_quality', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('insufficient', 'Insufficient'), ('estimated', 'Estimated')], db_index=True, default='insufficient', max_length=20, verbose_name='data quality')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='calculated at')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to='store.panel', verbose_name='panel')),
            ],
            options={
                'verbose_name': 'panel daily usage',
                'verbose_name_plural': 'panel daily usages',
                'ordering': ['-usage_date', 'panel__name'],
                'indexes': [models.Index(fields=['panel', 'usage_date'], name='store_panel_panel_i_c24e1c_idx'), models.Index(fields=['data_quality', 'usage_date'], name='store_panel_data_qu_dfbe24_idx')],
                'constraints': [models.UniqueConstraint(fields=('panel', 'usage_date', 'timezone'), name='unique_panel_daily_usage_per_timezone')],
            },
        ),
        migrations.CreateModel(
            name='PanelUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, verbose_name='captured at')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=20, verbose_name='status')),
                ('total_upload_bytes', models.BigIntegerField(default=0, verbose_name='total upload bytes')),
                ('total_download_bytes', models.BigIntegerField(default=0, verbose_name='total download bytes')),
                ('total_used_bytes', models.BigIntegerField(default=0, verbose_name='total used bytes')),
                ('clients_count', models.PositiveIntegerField(default=0, verbose_name='clients count')),
                ('online_clients_count', models.PositiveIntegerField(default=0, verbose_name='online clients count')),
                ('active_inbounds_count', models.PositiveIntegerField(default=0, verbose_name='active inbounds count')),
                ('checked_inbounds_count', models.PositiveIntegerField(default=0, verbose_name='checked inbounds count')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='store.panel', verbose_name='panel')),
            ],
            options={
                'verbose_name': 'panel usage snapshot',
                'verbose_name_plural': 'panel usage snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['panel', 'captured_at'], name='store_panel_panel_i_c8c2fd_idx'), models.Index(fields=['status', 'captured_at'], name='store_panel_status_72ee47_idx')],
            },
        ),
    ]
