# Generated by Django 6.0.4 on 2026-06-15 14:25

import django.db.models.deletion
import django.utils.timezone
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_store_panel_usage_active_user_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token hash')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('expires_at', models.DateTimeField(db_index=True, default=store.models.default_web_telegram_link_token_expiry, verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('source', models.CharField(choices=[('dashboard', 'Dashboard'), ('order_detail', 'Order detail'), ('after_checkout', 'After checkout'), ('admin', 'Admin')], db_index=True, default='dashboard', max_length=30, verbose_name='source')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_link_tokens', to='store.botuser', verbose_name='bot user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_telegram_link_tokens', to='store.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'web telegram link token',
                'verbose_name_plural': 'web telegram link tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status', 'expires_at'], name='store_webte_custome_0269be_idx'), models.Index(fields=['status', 'expires_at'], name='store_webte_status_b33121_idx'), models.Index(fields=['created_at'], name='store_webte_created_e34910_idx')],
            },
        ),
    ]
