# Generated by Django 6.0.4 on 2026-06-16 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_webtelegramlinktoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='audience_type',
            field=models.CharField(choices=[('all', 'All'), ('active_customers', 'Active customers'), ('customers_with_active_config', 'Customers with active config'), ('customers_without_order', 'Customers without order'), ('legacy_wizwiz_imported', 'کاربران قدیمی WizWiz'), ('loyal', 'Loyal'), ('good', 'Good'), ('top_buyer', 'Top buyer'), ('top_referrer', 'Top referrer'), ('inactive', 'Inactive'), ('no_order', 'No order')], db_index=True, default='all', max_length=40, verbose_name='audience type'),
        ),
        migrations.CreateModel(
            name='LegacyWizWizImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('source', models.CharField(db_index=True, default='wizwiz', max_length=40, verbose_name='source')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='title')),
                ('uploaded_file', models.FileField(upload_to='private/legacy_imports/wizwiz/', verbose_name='uploaded file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='file size')),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='file SHA256')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='uploaded', max_length=20, verbose_name='status')),
                ('mode', models.CharField(choices=[('users_only', 'Users only')], db_index=True, default='users_only', max_length=20, verbose_name='mode')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='analyzed at')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='applied at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('parsed_users_count', models.PositiveIntegerField(default=0, verbose_name='parsed users count')),
                ('valid_users_count', models.PositiveIntegerField(default=0, verbose_name='valid users count')),
                ('invalid_rows_count', models.PositiveIntegerField(default=0, verbose_name='invalid rows count')),
                ('duplicate_in_file_count', models.PositiveIntegerField(default=0, verbose_name='duplicate in file count')),
                ('existing_bot_users_count', models.PositiveIntegerField(default=0, verbose_name='existing bot users count')),
                ('existing_customers_count', models.PositiveIntegerField(default=0, verbose_name='existing customers count')),
                ('would_create_bot_users_count', models.PositiveIntegerField(default=0, verbose_name='would create bot users count')),
                ('would_create_customers_count', models.PositiveIntegerField(default=0, verbose_name='would create customers count')),
                ('admins_count', models.PositiveIntegerField(default=0, verbose_name='admins count')),
                ('agents_count', models.PositiveIntegerField(default=0, verbose_name='agents count')),
                ('wallet_positive_count', models.PositiveIntegerField(default=0, verbose_name='wallet positive count')),
                ('created_bot_users_count', models.PositiveIntegerField(default=0, verbose_name='created bot users count')),
                ('created_customers_count', models.PositiveIntegerField(default=0, verbose_name='created customers count')),
                ('linked_existing_count', models.PositiveIntegerField(default=0, verbose_name='linked existing count')),
                ('updated_existing_count', models.PositiveIntegerField(default=0, verbose_name='updated existing count')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='skipped count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='failed count')),
                ('skip_admins', models.BooleanField(default=True, verbose_name='skip admins')),
                ('import_agents', models.BooleanField(default=True, verbose_name='import agents')),
                ('only_agents', models.BooleanField(default=False, verbose_name='only agents')),
                ('only_wallet_positive', models.BooleanField(default=False, verbose_name='only wallet positive')),
                ('update_existing', models.BooleanField(default=False, verbose_name='update existing')),
                ('create_customers', models.BooleanField(default=True, verbose_name='create customers')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_wizwiz_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'legacy WizWiz import job',
                'verbose_name_plural': 'legacy WizWiz import jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegacyWizWizImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('source', models.CharField(db_index=True, default='wizwiz', max_length=40, verbose_name='source')),
                ('legacy_pk', models.CharField(blank=True, max_length=80, verbose_name='legacy PK')),
                ('telegram_user_id', models.CharField(db_index=True, max_length=80, verbose_name='Telegram user ID')),
                ('telegram_user_id_masked', models.CharField(blank=True, max_length=80, verbose_name='masked Telegram user ID')),
                ('old_name_masked', models.CharField(blank=True, max_length=160, verbose_name='old masked name')),
                ('old_username', models.CharField(blank=True, max_length=120, verbose_name='old username')),
                ('old_phone_masked', models.CharField(blank=True, max_length=80, verbose_name='old masked phone')),
                ('old_wallet', models.IntegerField(blank=True, null=True, verbose_name='old wallet')),
                ('old_is_admin', models.BooleanField(default=False, verbose_name='old is admin')),
                ('old_is_agent', models.BooleanField(default=False, verbose_name='old is agent')),
                ('old_freetrial', models.CharField(blank=True, max_length=120, verbose_name='old free trial')),
                ('old_refcode', models.CharField(blank=True, max_length=120, verbose_name='old refcode')),
                ('old_refered_by', models.CharField(blank=True, max_length=120, verbose_name='old referred by')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('would_create', 'Would create'), ('would_link_existing', 'Would link existing'), ('existing', 'Existing'), ('created', 'Created'), ('linked', 'Linked'), ('updated', 'Updated'), ('skipped', 'Skipped'), ('invalid', 'Invalid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30, verbose_name='status')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_wizwiz_import_rows', to='store.botuser', verbose_name='bot user')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_wizwiz_import_rows', to='store.customer', verbose_name='customer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='store.legacywizwizimportjob', verbose_name='job')),
            ],
            options={
                'verbose_name': 'legacy WizWiz import row',
                'verbose_name_plural': 'legacy WizWiz import rows',
                'ordering': ['job_id', 'created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportjob',
            index=models.Index(fields=['source', 'status', 'created_at'], name='store_legac_source_3997d4_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportjob',
            index=models.Index(fields=['file_sha256'], name='store_legac_file_sh_1341cb_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportrow',
            index=models.Index(fields=['job', 'status'], name='store_legac_job_id_30d7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportrow',
            index=models.Index(fields=['source', 'status'], name='store_legac_source_60c333_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportrow',
            index=models.Index(fields=['telegram_user_id'], name='store_legac_telegra_182248_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportrow',
            index=models.Index(fields=['customer', 'status'], name='store_legac_custome_9e44aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='legacywizwizimportrow',
            constraint=models.UniqueConstraint(fields=('job', 'telegram_user_id'), name='unique_legacy_wizwiz_row_per_job_user'),
        ),
    ]
