# Generated by Django 6.0.4 on 2026-06-16 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_broadcastmessage_audience_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyWizWizImportMessageBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('text', models.TextField(verbose_name='message text')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total recipients')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='sent count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='failed count')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='skipped count')),
                ('blocked_count', models.PositiveIntegerField(default=0, verbose_name='blocked count')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_wizwiz_import_message_batches', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_batches', to='store.legacywizwizimportjob', verbose_name='job')),
            ],
            options={
                'verbose_name': 'legacy WizWiz import message batch',
                'verbose_name_plural': 'legacy WizWiz import message batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegacyWizWizImportMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('telegram_user_id_masked', models.CharField(blank=True, max_length=80, verbose_name='masked Telegram user ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='store.legacywizwizimportmessagebatch', verbose_name='batch')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_wizwiz_import_message_recipients', to='store.botuser', verbose_name='bot user')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_wizwiz_import_message_recipients', to='store.customer', verbose_name='customer')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipients', to='store.legacywizwizimportrow', verbose_name='import row')),
            ],
            options={
                'verbose_name': 'legacy WizWiz import message recipient',
                'verbose_name_plural': 'legacy WizWiz import message recipients',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportmessagebatch',
            index=models.Index(fields=['job', 'status'], name='store_legac_job_id_a938ae_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportmessagebatch',
            index=models.Index(fields=['status', 'created_at'], name='store_legac_status_52875c_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportmessagerecipient',
            index=models.Index(fields=['batch', 'status'], name='store_legac_batch_i_c03721_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportmessagerecipient',
            index=models.Index(fields=['row', 'status'], name='store_legac_row_id_5a013c_idx'),
        ),
        migrations.AddIndex(
            model_name='legacywizwizimportmessagerecipient',
            index=models.Index(fields=['customer', 'status'], name='store_legac_custome_da84e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='legacywizwizimportmessagerecipient',
            constraint=models.UniqueConstraint(fields=('batch', 'row'), name='unique_legacy_wizwiz_message_recipient_per_row'),
        ),
    ]
