# Generated by Django 6.0.4 on 2026-06-16 20:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_legacywizwizimportmessagebatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='ai_revenue_optimizer_enabled',
            field=models.BooleanField(default=True, verbose_name='AI revenue optimizer enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='renewal_engine_enabled',
            field=models.BooleanField(default=True, verbose_name='renewal engine enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='retention_engine_enabled',
            field=models.BooleanField(default=True, verbose_name='retention engine enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='retention_offer_cooldown_hours',
            field=models.PositiveIntegerField(default=72, validators=[django.core.validators.MinValueValidator(1)], verbose_name='retention offer cooldown hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_engine_dry_run',
            field=models.BooleanField(default=True, help_text='When enabled, revenue offers are logged but not sent.', verbose_name='revenue engine dry run'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_engine_enabled',
            field=models.BooleanField(default=True, help_text='Master kill switch for all revenue engine messages.', verbose_name='revenue engine enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_engine_quiet_hours_enabled',
            field=models.BooleanField(default=False, verbose_name='revenue engine quiet hours enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_engine_quiet_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='revenue engine quiet hours end'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_engine_quiet_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='revenue engine quiet hours start'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_engine_timezone',
            field=models.CharField(blank=True, default='Asia/Tehran', max_length=64, verbose_name='revenue engine time zone'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_max_offers_per_user_per_day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='revenue max offers per user per day'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_max_offers_per_user_per_week',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='revenue max offers per user per week'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_max_total_offers_per_day',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)], verbose_name='revenue max total offers per day'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_min_ai_confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='revenue minimum AI confidence'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_offer_cooldown_hours',
            field=models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)], verbose_name='revenue offer cooldown hours'),
        ),
        migrations.AddField(
            model_name='store',
            name='revenue_optimization_enabled',
            field=models.BooleanField(default=True, verbose_name='revenue optimization enabled'),
        ),
        migrations.AddField(
            model_name='store',
            name='upsell_engine_enabled',
            field=models.BooleanField(default=True, verbose_name='upsell engine enabled'),
        ),
        migrations.CreateModel(
            name='RevenueOfferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('renewal', 'Renewal'), ('upsell', 'Upsell'), ('retention', 'Retention'), ('silent_active', 'Silent active'), ('ai_optimizer', 'AI optimizer')], db_index=True, max_length=30, verbose_name='engine type')),
                ('event_type', models.CharField(db_index=True, max_length=80, verbose_name='event type')),
                ('offer_type', models.CharField(db_index=True, max_length=80, verbose_name='offer type')),
                ('variant', models.CharField(blank=True, max_length=40, verbose_name='variant')),
                ('decision_source', models.CharField(choices=[('rule', 'Rule'), ('optimization', 'Optimization'), ('ai', 'AI'), ('fallback', 'Fallback')], db_index=True, default='rule', max_length=30, verbose_name='decision source')),
                ('status', models.CharField(choices=[('dry_run', 'Dry run'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('suppressed', 'Suppressed'), ('failed', 'Failed'), ('converted', 'Converted')], db_index=True, default='skipped', max_length=30, verbose_name='status')),
                ('skip_reason', models.CharField(blank=True, max_length=120, verbose_name='skip reason')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='AI confidence')),
                ('predicted_purchase_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='predicted purchase probability')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='converted at')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_offer_logs', to='store.botuser', verbose_name='bot user')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_offer_logs', to='store.customer', verbose_name='customer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_offer_logs', to='store.store', verbose_name='store')),
                ('vpn_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_offer_logs', to='store.vpnclient', verbose_name='VPN client')),
            ],
            options={
                'verbose_name': 'revenue offer log',
                'verbose_name_plural': 'revenue offer logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='store_reven_custome_a11b4c_idx'), models.Index(fields=['engine_type', 'created_at'], name='store_reven_engine__ad06de_idx'), models.Index(fields=['status', 'created_at'], name='store_reven_status_50b026_idx'), models.Index(fields=['event_type', 'created_at'], name='store_reven_event_t_f192fa_idx')],
            },
        ),
    ]
