# Generated by Django 6.0.4 on 2026-06-23 18:50

from django.db import migrations, models


def backfill_xui_scope(apps, schema_editor):
    Inbound = apps.get_model("store", "Inbound")
    VPNClient = apps.get_model("store", "VPNClient")

    for inbound in Inbound.objects.all().iterator():
        node_id = (getattr(inbound, "xui_node_id", "") or "").strip()
        if not (getattr(inbound, "xui_source", "") or "").strip():
            inbound.xui_source = "local"
        if not (getattr(inbound, "xui_remote_key", "") or "").strip():
            inbound.xui_remote_key = f"{inbound.panel_id or ''}:{node_id or 'local'}:{inbound.inbound_id}"
        inbound.is_synced_from_node = bool(node_id and inbound.xui_source == "synchronized_node")
        inbound.save(update_fields=["xui_source", "xui_remote_key", "is_synced_from_node"])

    for vpn_client in VPNClient.objects.select_related("inbound", "inbound__panel").all().iterator():
        inbound = getattr(vpn_client, "inbound", None)
        if not inbound:
            continue
        node_id = (getattr(vpn_client, "xui_node_id", "") or "").strip() or (getattr(inbound, "xui_node_id", "") or "").strip()
        identity = (
            str(getattr(vpn_client, "uuid", "") or "").strip()
            or str(getattr(vpn_client, "xui_email", "") or "").strip()
            or str(getattr(vpn_client, "username", "") or "").strip()
            or str(getattr(vpn_client, "pk", "") or "")
        )
        if not (getattr(vpn_client, "remote_client_key", "") or "").strip() and identity:
            vpn_client.remote_client_key = (
                f"{getattr(inbound, 'panel_id', '') or ''}:{node_id or 'local'}:{inbound.inbound_id}:{identity}"
            )
        vpn_client.xui_node_id = node_id
        vpn_client.save(update_fields=["xui_node_id", "remote_client_key"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_store_product_neutral_defaults'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inbound',
            name='unique_inbound_id_per_panel',
        ),
        migrations.AddField(
            model_name='inbound',
            name='is_synced_from_node',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is synced from node'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='xui_node_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='X-UI node ID'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='xui_node_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='X-UI node name'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='xui_remote_key',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='X-UI remote key'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='xui_source',
            field=models.CharField(choices=[('local', 'Local'), ('synchronized_node', 'Synchronized node')], db_index=True, default='local', max_length=30, verbose_name='X-UI source'),
        ),
        migrations.AddField(
            model_name='panel',
            name='capability_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='capability metadata'),
        ),
        migrations.AddField(
            model_name='panel',
            name='capability_profile',
            field=models.CharField(blank=True, choices=[('legacy_single_node', 'Legacy single-node'), ('modern_single_node', 'Modern single-node'), ('modern_multi_node', 'Modern multi-node'), ('unknown_safe', 'Unknown safe')], db_index=True, max_length=50, verbose_name='capability profile'),
        ),
        migrations.AddField(
            model_name='panel',
            name='detected_xui_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='detected X-UI version'),
        ),
        migrations.AddField(
            model_name='panel',
            name='last_capability_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last capability check at'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='remote_client_key',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='remote client key'),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='xui_node_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='X-UI node ID'),
        ),
        migrations.RunPython(backfill_xui_scope, noop_reverse),
        migrations.AddIndex(
            model_name='vpnclient',
            index=models.Index(fields=['inbound', 'xui_node_id', 'remote_client_key'], name='store_vpncl_inbound_f055c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='inbound',
            constraint=models.UniqueConstraint(fields=('panel', 'xui_node_id', 'inbound_id'), name='unique_inbound_remote_scope_per_panel'),
        ),
    ]
