# Generated by Django 6.0.4 on 2026-06-23 20:15

from django.conf import settings
from django.db import migrations, models


def backfill_order_provisioning_state(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    VPNClient = apps.get_model("store", "VPNClient")
    for order in Order.objects.only("pk", "status", "uuid", "verified_at", "updated_at").iterator():
        has_client = VPNClient.objects.filter(order_id=order.pk).exists()
        if order.status in {"rejected", "cancelled"}:
            provisioning_status = "not_required"
            provisioned_at = None
            error = ""
        elif has_client or order.uuid:
            provisioning_status = "provisioned"
            provisioned_at = order.verified_at or order.updated_at
            error = ""
        elif order.status == "completed":
            provisioning_status = "failed"
            provisioned_at = None
            error = "Completed order has no local VPN client/config record."
        else:
            provisioning_status = "pending"
            provisioned_at = None
            error = ""
        Order.objects.filter(pk=order.pk).update(
            provisioning_status=provisioning_status,
            provisioned_at=provisioned_at,
            last_provisioning_error=error,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_remove_inbound_unique_inbound_id_per_panel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_provisioning_error',
            field=models.TextField(blank=True, verbose_name='last provisioning error'),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='provisioned at'),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='provisioning attempts'),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=160, verbose_name='provisioning idempotency key'),
        ),
        migrations.AddField(
            model_name='order',
            name='provisioning_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('provisioning', 'Provisioning'), ('provisioned', 'Provisioned'), ('failed', 'Failed')], db_index=True, default='not_required', max_length=20, verbose_name='provisioning status'),
        ),
        migrations.RunPython(backfill_order_provisioning_state, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['provisioning_status', 'created_at'], name='store_order_provisi_914794_idx'),
        ),
    ]
