# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0052_order_last_provisioning_error_order_provisioned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnclient",
            name="last_remote_check_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="last remote check at"),
        ),
        migrations.AddField(
            model_name="vpnclient",
            name="last_remote_check_batch_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name="last remote check batch ID"),
        ),
        migrations.AddField(
            model_name="vpnclient",
            name="last_remote_check_error",
            field=models.CharField(blank=True, max_length=300, verbose_name="last remote check error"),
        ),
        migrations.AddField(
            model_name="vpnclient",
            name="last_remote_check_scope",
            field=models.JSONField(blank=True, default=dict, verbose_name="last remote check scope"),
        ),
        migrations.AddField(
            model_name="vpnclient",
            name="last_remote_check_status",
            field=models.CharField(
                choices=[
                    ("not_checked", "Not checked"),
                    ("remote_active", "Remote active"),
                    ("remote_disabled", "Remote disabled"),
                    ("remote_missing", "Remote missing"),
                    ("panel_unreachable", "Panel unreachable"),
                    ("inbound_missing", "Inbound missing"),
                    ("ambiguous", "Ambiguous"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="not_checked",
                max_length=30,
                verbose_name="last remote check status",
            ),
        ),
        migrations.AddIndex(
            model_name="vpnclient",
            index=models.Index(
                fields=["last_remote_check_status", "last_remote_check_at"],
                name="store_vpncl_last_re_7d8d4b_idx",
            ),
        ),
        migrations.AlterField(
            model_name="vpnclientactionlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user_delete", "User delete"),
                    ("admin_delete", "Admin delete"),
                    ("admin_update_traffic", "Admin update traffic"),
                    ("admin_update_expiry", "Admin update expiry"),
                    ("admin_update_traffic_and_expiry", "Admin update traffic and expiry"),
                    ("admin_refresh_link", "Admin refresh link"),
                    ("admin_reconcile_check", "Admin reconcile check"),
                    ("admin_soft_delete_remote_missing", "Admin soft-delete remote missing"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="action",
            ),
        ),
    ]
