# Generated by Django 6.0.4 on 2026-06-27 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_vpnclient_remote_reconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QasedakBackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('backup_type', models.CharField(choices=[('db_only', 'Database only'), ('db_and_media', 'Database and media'), ('full_transfer', 'Server transfer package')], db_index=True, default='db_only', max_length=20, verbose_name='backup type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('file_path', models.CharField(blank=True, max_length=600, verbose_name='file path')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='file size')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA256')),
                ('includes_media', models.BooleanField(default=False, verbose_name='includes media')),
                ('includes_env', models.BooleanField(default=False, verbose_name='includes env')),
                ('includes_system', models.BooleanField(default=False, verbose_name='includes system')),
                ('safe_summary', models.JSONField(blank=True, default=dict, verbose_name='safe summary')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qasedak_backup_jobs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Qasedak backup job',
                'verbose_name_plural': 'Qasedak backup jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='store_qased_status_6a1230_idx'), models.Index(fields=['backup_type', 'created_at'], name='store_qased_backup__4080fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='QasedakRestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('uploaded_file_path', models.CharField(blank=True, max_length=600, verbose_name='uploaded file path')),
                ('uploaded_file_name', models.CharField(blank=True, max_length=255, verbose_name='uploaded file name')),
                ('uploaded_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='uploaded SHA256')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('validation_failed', 'Validation failed'), ('ready', 'Ready'), ('restore_command_generated', 'Restore command generated'), ('restoring', 'Restoring'), ('restored', 'Restored'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='uploaded', max_length=32, verbose_name='status')),
                ('validation_summary', models.JSONField(blank=True, default=dict, verbose_name='validation summary')),
                ('restore_plan', models.JSONField(blank=True, default=dict, verbose_name='restore plan')),
                ('pre_restore_backup_path', models.CharField(blank=True, max_length=600, verbose_name='pre-restore backup path')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('includes_env', models.BooleanField(default=False, verbose_name='includes env')),
                ('includes_media', models.BooleanField(default=False, verbose_name='includes media')),
                ('requires_service_restart', models.BooleanField(default=True, verbose_name='requires service restart')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validated at')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='restored at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qasedak_restore_jobs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Qasedak restore job',
                'verbose_name_plural': 'Qasedak restore jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='store_qased_status_e1c84a_idx')],
            },
        ),
    ]
