# Generated by Django 6.0.4 on 2026-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_tenant_onboarding_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='multi_inbound_bundle',
            field=models.BooleanField(db_index=True, default=False, help_text='When enabled for modern 3X-UI panels, all active plan routes are provisioned as one client attached to multiple inbounds.', verbose_name='multi inbound bundle'),
        ),
    ]
