# Generated by Codex on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0058_plan_multi_inbound_bundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="family",
            field=models.CharField(
                choices=[
                    ("xui", "X-UI / Sanaei"),
                    ("marzban", "Marzban"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="xui",
                help_text="Panel API family. Existing Sanaei/3X-UI panels use X-UI.",
                max_length=30,
                verbose_name="panel family",
            ),
        ),
    ]
