# Generated by Django 6.0.4 on 2026-08-04 16:24

import django.db.models.deletion
import django.utils.timezone
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_panel_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('raw_link', models.TextField(verbose_name='raw link')),
                ('normalized_link', models.TextField(blank=True, verbose_name='normalized link')),
                ('normalized_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='normalized hash')),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMess'), ('trojan', 'Trojan'), ('ss', 'Shadowsocks'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20, verbose_name='protocol')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='remark')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='host')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='port')),
                ('source_type', models.CharField(choices=[('panel_generated', 'Panel generated'), ('manual', 'Manual'), ('imported_subscription', 'Imported subscription'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30, verbose_name='source type')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('source_inbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_links', to='store.inbound', verbose_name='source inbound')),
                ('source_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_links', to='store.panel', verbose_name='source panel')),
                ('vpn_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_links', to='store.vpnclient', verbose_name='VPN client')),
            ],
            options={
                'verbose_name': 'config link',
                'verbose_name_plural': 'config links',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('token', models.CharField(default=store.models.generate_subscription_cup_token, editable=False, max_length=64, unique=True, verbose_name='token')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expires at')),
                ('traffic_limit_bytes', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='traffic limit bytes')),
                ('device_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='device limit')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_cups', to='store.customer', verbose_name='customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_cups', to='store.order', verbose_name='order')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_cups', to='store.plan', verbose_name='plan')),
                ('vpn_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_cups', to='store.vpnclient', verbose_name='VPN client')),
            ],
            options={
                'verbose_name': 'subscription cup',
                'verbose_name_plural': 'subscription cups',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('added_reason', models.CharField(blank=True, max_length=100, verbose_name='added reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('config_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup_items', to='store.configlink', verbose_name='config link')),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.subscriptioncup', verbose_name='subscription cup')),
            ],
            options={
                'verbose_name': 'cup item',
                'verbose_name_plural': 'cup items',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='configlink',
            index=models.Index(fields=['protocol', 'is_active'], name='store_confi_protoco_d6b01b_idx'),
        ),
        migrations.AddIndex(
            model_name='configlink',
            index=models.Index(fields=['source_type', 'created_at'], name='store_confi_source__9b4939_idx'),
        ),
        migrations.AddIndex(
            model_name='configlink',
            index=models.Index(fields=['vpn_client', 'is_active'], name='store_confi_vpn_cli_65008f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncup',
            index=models.Index(fields=['customer', 'status'], name='store_subsc_custome_874051_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncup',
            index=models.Index(fields=['order', 'status'], name='store_subsc_order_i_b44df4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncup',
            index=models.Index(fields=['vpn_client', 'status'], name='store_subsc_vpn_cli_5b5585_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncup',
            index=models.Index(fields=['status', 'expires_at'], name='store_subsc_status_7077a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cupitem',
            index=models.Index(fields=['cup', 'is_active', 'position'], name='store_cupit_cup_id_74fbd5_idx'),
        ),
        migrations.AddIndex(
            model_name='cupitem',
            index=models.Index(fields=['config_link', 'is_active'], name='store_cupit_config__423968_idx'),
        ),
    ]
