# Generated by Django 6.0.4 on 2026-08-05 18:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_subscription_cups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInventoryPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('traffic_limit_gb', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='traffic limit GB')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration days')),
                ('allocation_mode', models.CharField(choices=[('exclusive', 'Exclusive'), ('shared_limited', 'Shared limited'), ('shared_unlimited', 'Shared unlimited')], db_index=True, default='exclusive', max_length=30, verbose_name='allocation mode')),
                ('max_allocations_per_asset', models.PositiveIntegerField(blank=True, null=True, verbose_name='max allocations per asset')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, verbose_name='priority')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('connected_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_inventory_pools', to='store.plan', verbose_name='connected plan')),
            ],
            options={
                'verbose_name': 'config inventory pool',
                'verbose_name_plural': 'config inventory pools',
                'ordering': ['priority', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfigInventoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('raw_link', models.TextField(verbose_name='raw link')),
                ('normalized_link', models.TextField(blank=True, verbose_name='normalized link')),
                ('normalized_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='normalized hash')),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMess'), ('trojan', 'Trojan'), ('ss', 'Shadowsocks'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20, verbose_name='protocol')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='remark')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='host')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='port')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('assigned', 'Assigned'), ('disabled', 'Disabled'), ('expired', 'Expired'), ('burned', 'Burned')], db_index=True, default='available', max_length=20, verbose_name='status')),
                ('traffic_limit_gb', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='traffic limit GB')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expires at')),
                ('max_allocations', models.PositiveIntegerField(blank=True, null=True, verbose_name='max allocations')),
                ('current_allocations', models.PositiveIntegerField(db_index=True, default=0, verbose_name='current allocations')),
                ('source_batch', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='source batch')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='store.configinventorypool', verbose_name='pool')),
            ],
            options={
                'verbose_name': 'config inventory asset',
                'verbose_name_plural': 'config inventory assets',
                'ordering': ['pool__priority', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CupFulfillmentRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, verbose_name='priority')),
                ('failure_policy', models.CharField(choices=[('strict', 'Strict'), ('partial_allowed', 'Partial allowed')], db_index=True, default='strict', max_length=30, verbose_name='failure policy')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup_fulfillment_recipes', to='store.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'cup fulfillment recipe',
                'verbose_name_plural': 'cup fulfillment recipes',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CupFillerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('position', models.PositiveIntegerField(db_index=True, default=1, verbose_name='position')),
                ('source_type', models.CharField(choices=[('panel_inbounds', 'Panel inbounds'), ('inventory_pool', 'Inventory pool')], db_index=True, max_length=30, verbose_name='source type')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('allocation_mode', models.CharField(blank=True, choices=[('exclusive', 'Exclusive'), ('shared_limited', 'Shared limited'), ('shared_unlimited', 'Shared unlimited')], max_length=30, verbose_name='allocation mode override')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('inbounds', models.ManyToManyField(blank=True, related_name='cup_filler_rules', to='store.inbound', verbose_name='inbounds')),
                ('inventory_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_filler_rules', to='store.configinventorypool', verbose_name='inventory pool')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_filler_rules', to='store.panel', verbose_name='panel')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='store.cupfulfillmentrecipe', verbose_name='recipe')),
            ],
            options={
                'verbose_name': 'cup filler rule',
                'verbose_name_plural': 'cup filler rules',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfigAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('allocation_mode', models.CharField(choices=[('exclusive', 'Exclusive'), ('shared_limited', 'Shared limited'), ('shared_unlimited', 'Shared unlimited')], db_index=True, max_length=30, verbose_name='allocation mode')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('allocated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='allocated at')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='released at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('cup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_allocations', to='store.subscriptioncup', verbose_name='subscription cup')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_allocations', to='store.order', verbose_name='order')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='store.configinventoryasset', verbose_name='asset')),
            ],
            options={
                'verbose_name': 'config allocation',
                'verbose_name_plural': 'config allocations',
                'ordering': ['-allocated_at', '-id'],
                'indexes': [models.Index(fields=['asset', 'status'], name='store_confi_asset_i_784f9a_idx'), models.Index(fields=['cup', 'status'], name='store_confi_cup_id_81f36c_idx'), models.Index(fields=['order', 'status'], name='store_confi_order_i_b5c8a6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='configinventorypool',
            index=models.Index(fields=['connected_plan', 'is_active', 'priority'], name='store_confi_connect_73317b_idx'),
        ),
        migrations.AddIndex(
            model_name='configinventorypool',
            index=models.Index(fields=['is_active', 'priority'], name='store_confi_is_acti_798720_idx'),
        ),
        migrations.AddIndex(
            model_name='configinventoryasset',
            index=models.Index(fields=['pool', 'status', 'created_at'], name='store_confi_pool_id_ee99cc_idx'),
        ),
        migrations.AddIndex(
            model_name='configinventoryasset',
            index=models.Index(fields=['pool', 'normalized_hash'], name='store_confi_pool_id_41ad46_idx'),
        ),
        migrations.AddIndex(
            model_name='configinventoryasset',
            index=models.Index(fields=['status', 'expires_at'], name='store_confi_status_1bbcff_idx'),
        ),
        migrations.AddIndex(
            model_name='cupfulfillmentrecipe',
            index=models.Index(fields=['plan', 'is_active', 'priority'], name='store_cupfu_plan_id_8ffad2_idx'),
        ),
        migrations.AddIndex(
            model_name='cupfulfillmentrecipe',
            index=models.Index(fields=['is_active', 'priority'], name='store_cupfu_is_acti_5e1e28_idx'),
        ),
        migrations.AddIndex(
            model_name='cupfillerrule',
            index=models.Index(fields=['recipe', 'is_active', 'position'], name='store_cupfi_recipe__754885_idx'),
        ),
        migrations.AddIndex(
            model_name='cupfillerrule',
            index=models.Index(fields=['source_type', 'is_active'], name='store_cupfi_source__ad44ea_idx'),
        ),
    ]
