# Generated by Django 6.0.4 on 2026-08-23 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_config_inventory_fulfillment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelHealthAlertSettings',
            fields=[
            ],
            options={
                'verbose_name': 'هشدار سلامت پنل به ربات',
                'verbose_name_plural': 'هشدار سلامت پنل\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.store',),
        ),
        migrations.AddField(
            model_name='panel',
            name='alert_repeat_interval_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional override for repeated failure alerts. Leave blank to use Store settings.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='فاصله تکرار هشدار برای این پنل'),
        ),
        migrations.AddField(
            model_name='panel',
            name='failure_threshold_count',
            field=models.PositiveIntegerField(blank=True, help_text='Optional override for failures required before alerting. Leave blank to use Store settings.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد خطای پشت\u200cسرهم برای این پنل'),
        ),
        migrations.AddField(
            model_name='panel',
            name='health_alert_enabled',
            field=models.BooleanField(default=True, help_text='Allow this panel to send Telegram admin health alerts when global alerts are enabled.', verbose_name='هشدار سلامت فعال'),
        ),
        migrations.AddField(
            model_name='panelhealthstatus',
            name='last_alert_error_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='last alert error code'),
        ),
        migrations.AddField(
            model_name='panelhealthstatus',
            name='last_alert_message_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='last alert message hash'),
        ),
        migrations.AddField(
            model_name='panelhealthstatus',
            name='last_recovery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last recovery at'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_health_alert_check_interval_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Intended scheduler interval in minutes. Scheduling is configured outside Django.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='فاصله بررسی سلامت پنل'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_health_alert_failure_threshold_count',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد خطای پشت\u200cسرهم قبل از ارسال هشدار'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_health_alert_repeat_interval_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='فاصله تکرار هشدار برای خطای تکراری'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_health_alerts_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for Telegram admin alerts when panel health checks fail.', verbose_name='فعال\u200cسازی هشدار خرابی پنل'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_health_quiet_hours_enabled',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی ساعات سکوت'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_health_quiet_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='پایان ساعات سکوت'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_health_quiet_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='شروع ساعات سکوت'),
        ),
        migrations.AddField(
            model_name='store',
            name='panel_health_recovery_alert_enabled',
            field=models.BooleanField(default=True, verbose_name='ارسال پیام بعد از درست شدن پنل'),
        ),
    ]
