# Generated by Django 6.0.4 on 2026-08-23 20:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_panelhealthalertsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeliveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('delivery_mode', models.CharField(choices=[('GLOBAL_FALLBACK', 'Global fallback'), ('DIRECT_LINKS', 'Direct links'), ('SUBSCRIPTION', 'Subscription')], db_index=True, default='GLOBAL_FALLBACK', max_length=30, verbose_name='delivery mode')),
                ('failure_policy', models.CharField(choices=[('strict', 'Strict'), ('partial_allowed', 'Partial allowed')], db_index=True, default='strict', max_length=30, verbose_name='failure policy')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_config', to='store.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'plan delivery config',
                'verbose_name_plural': 'plan delivery configs',
            },
        ),
        migrations.CreateModel(
            name='PlanDeliverySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('source_type', models.CharField(choices=[('PANEL_INBOUND', 'Panel inbound'), ('INVENTORY_POOL', 'Inventory pool')], db_index=True, max_length=30, verbose_name='source type')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='label')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, verbose_name='priority')),
                ('is_fallback', models.BooleanField(db_index=True, default=False, verbose_name='is fallback')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('delivery_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='store.plandeliveryconfig', verbose_name='delivery config')),
                ('inbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_delivery_sources', to='store.inbound', verbose_name='inbound')),
                ('inventory_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_delivery_sources', to='store.configinventorypool', verbose_name='inventory pool')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_delivery_sources', to='store.panel', verbose_name='panel')),
            ],
            options={
                'verbose_name': 'plan delivery source',
                'verbose_name_plural': 'plan delivery sources',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='plandeliveryconfig',
            index=models.Index(fields=['delivery_mode', 'active'], name='store_pland_deliver_5e64cd_idx'),
        ),
        migrations.AddIndex(
            model_name='plandeliverysource',
            index=models.Index(fields=['delivery_config', 'active', 'priority'], name='store_pland_deliver_753fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='plandeliverysource',
            index=models.Index(fields=['source_type', 'active'], name='store_pland_source__b44c86_idx'),
        ),
        migrations.AddIndex(
            model_name='plandeliverysource',
            index=models.Index(fields=['is_fallback', 'priority'], name='store_pland_is_fall_6abf30_idx'),
        ),
    ]
