# Generated by Codex on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0063_plandeliveryconfig_plandeliverysource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panel",
            name="family",
            field=models.CharField(
                choices=[
                    ("xui", "X-UI / Sanaei"),
                    ("marzban", "Marzban"),
                    ("pasarguard", "PasarGuard / پاسارگارد"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="xui",
                help_text="Panel API family. Existing Sanaei/3X-UI panels use X-UI.",
                max_length=30,
                verbose_name="panel family",
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="capability_profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("legacy_single_node", "Legacy single-node"),
                    ("modern_single_node", "Modern single-node"),
                    ("modern_multi_node", "Modern multi-node"),
                    ("pasarguard_groups", "PasarGuard groups"),
                    ("unknown_safe", "Unknown safe"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="capability profile",
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="username",
            field=models.CharField(blank=True, max_length=100, verbose_name="username"),
        ),
        migrations.AlterField(
            model_name="panel",
            name="password",
            field=models.CharField(max_length=500, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="inbound",
            name="xui_source",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("synchronized_node", "Synchronized node"),
                    ("pasarguard_group", "PasarGuard group"),
                ],
                db_index=True,
                default="local",
                max_length=30,
                verbose_name="X-UI source",
            ),
        ),
        migrations.AddField(
            model_name="inbound",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="metadata"),
        ),
        migrations.AlterField(
            model_name="order",
            name="direct_link",
            field=models.TextField(blank=True, null=True, verbose_name="direct link"),
        ),
        migrations.AlterField(
            model_name="vpnclient",
            name="direct_link",
            field=models.TextField(blank=True, null=True, verbose_name="direct link"),
        ),
    ]
