# Generated by Codex on 2026-08-30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0064_pasarguard_panel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configlink",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("vless", "VLESS"),
                    ("vmess", "VMess"),
                    ("trojan", "Trojan"),
                    ("ss", "Shadowsocks"),
                    ("hysteria2", "Hysteria2"),
                    ("wireguard", "WireGuard"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
                verbose_name="protocol",
            ),
        ),
        migrations.AlterField(
            model_name="configinventoryasset",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("vless", "VLESS"),
                    ("vmess", "VMess"),
                    ("trojan", "Trojan"),
                    ("ss", "Shadowsocks"),
                    ("hysteria2", "Hysteria2"),
                    ("wireguard", "WireGuard"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=20,
                verbose_name="protocol",
            ),
        ),
        migrations.AlterField(
            model_name="configlink",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("panel_generated", "Panel generated"),
                    ("manual", "Manual"),
                    ("imported_subscription", "Imported subscription"),
                    ("external_subscription", "External subscription"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                max_length=30,
                verbose_name="source type",
            ),
        ),
        migrations.CreateModel(
            name="ExternalSubscriptionFeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="created at")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="updated at")),
                ("provider", models.CharField(db_index=True, max_length=50, verbose_name="provider")),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("remote_identity_ref", models.CharField(blank=True, max_length=160, verbose_name="remote identity reference")),
                ("protected_subscription_url", models.TextField(blank=True, verbose_name="protected upstream subscription URL")),
                ("resolved_filter_policy", models.JSONField(blank=True, default=dict, verbose_name="resolved filter policy")),
                (
                    "refresh_interval_hours",
                    models.PositiveIntegerField(
                        default=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="refresh interval hours",
                    ),
                ),
                ("next_refresh_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="next refresh at")),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True, verbose_name="last attempt at")),
                ("last_success_at", models.DateTimeField(blank=True, null=True, verbose_name="last success at")),
                ("consecutive_failures", models.PositiveIntegerField(default=0, verbose_name="consecutive failures")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="healthy",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("last_good_config_count", models.PositiveIntegerField(default=0, verbose_name="last good config count")),
                ("last_seen_upstream_count", models.PositiveIntegerField(default=0, verbose_name="last seen upstream count")),
                ("last_filtered_count", models.PositiveIntegerField(default=0, verbose_name="last filtered count")),
                ("last_error_code", models.CharField(blank=True, db_index=True, max_length=80, verbose_name="last error code")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "cup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_feeds",
                        to="store.subscriptioncup",
                        verbose_name="subscription cup",
                    ),
                ),
                (
                    "delivery_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_subscription_feeds",
                        to="store.plandeliverysource",
                        verbose_name="originating plan delivery source",
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_subscription_feeds",
                        to="store.panel",
                        verbose_name="panel",
                    ),
                ),
                (
                    "vpn_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_subscription_feeds",
                        to="store.vpnclient",
                        verbose_name="VPN client",
                    ),
                ),
            ],
            options={
                "verbose_name": "external subscription feed",
                "verbose_name_plural": "external subscription feeds",
                "ordering": ["next_refresh_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="configlink",
            name="external_feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="config_links",
                to="store.externalsubscriptionfeed",
                verbose_name="external subscription feed",
            ),
        ),
        migrations.AddIndex(
            model_name="externalsubscriptionfeed",
            index=models.Index(fields=["provider", "status"], name="store_exter_provide_d547d8_idx"),
        ),
        migrations.AddIndex(
            model_name="externalsubscriptionfeed",
            index=models.Index(fields=["active", "next_refresh_at"], name="store_exter_active_c5f190_idx"),
        ),
        migrations.AddIndex(
            model_name="externalsubscriptionfeed",
            index=models.Index(fields=["cup", "status"], name="store_exter_cup_id_5157ea_idx"),
        ),
        migrations.AddIndex(
            model_name="externalsubscriptionfeed",
            index=models.Index(fields=["panel", "status"], name="store_exter_panel_i_49bada_idx"),
        ),
        migrations.AddIndex(
            model_name="configlink",
            index=models.Index(fields=["external_feed", "is_active"], name="store_confi_externa_858219_idx"),
        ),
    ]
