# Generated by Django 6.0.4 on 2026-08-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_dynamic_subscription_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound',
            name='last_verification_error_code',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='last verification error code'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='last_verified_config_count',
            field=models.PositiveIntegerField(default=0, verbose_name='last verified config count'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='verification_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verification attempted at'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='verification_method',
            field=models.CharField(blank=True, max_length=80, verbose_name='verification method'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified_sellable', 'Verified sellable'), ('verification_failed', 'Verification failed')], db_index=True, default='unverified', max_length=30, verbose_name='sellability verification status'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='verified at'),
        ),
    ]
