# Generated by Django 6.0.4 on 2026-09-29 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_external_feed_hourly_refresh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='order_auto_approve_enabled',
            field=models.BooleanField(default=False, verbose_name='تأیید خودکار ۵ دقیقه پس از ثبت رسید'),
        ),
        migrations.AddField(
            model_name='store',
            name='order_auto_approve_enabled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='order_automation_last_run_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='order_review_reminders_enabled',
            field=models.BooleanField(default=True, verbose_name='یادآوری سفارش\u200cهای منتظر بررسی'),
        ),
        migrations.CreateModel(
            name='OrderAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('reminder_stage', models.PositiveSmallIntegerField(default=0)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('review_status', models.CharField(blank=True, choices=[('pending', 'منتظر تطبیق'), ('verified', 'تطبیق\u200cشده'), ('cancelling', 'در حال لغو'), ('cancelled', 'لغوشده'), ('cancel_failed', 'لغو ناقص؛ نیازمند پیگیری')], db_index=True, default='', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('revoked_client_ids', models.JSONField(blank=True, default=list)),
                ('cancellation_notified_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_notification_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_notification_status', models.CharField(blank=True, max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='store.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیگیری و تأیید خودکار سفارش',
                'verbose_name_plural': 'پیگیری و تأیید خودکار سفارش\u200cها',
            },
        ),
    ]
