# Generated by Django 6.0.4 on 2026-10-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_order_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsubscriptionfeed',
            name='refresh_lease_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='externalsubscriptionfeed',
            name='refresh_token',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
