
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.health import health
from store.admin_backup_restore import (
    backup_center,
    backup_create,
    backup_delete,
    backup_download,
    restore_command,
    restore_detail,
    restore_upload,
    restore_validate,
)
from store.admin_views import (
    card_receipts_report,
    campaign_audience,
    campaign_confirm,
    campaign_export,
    campaign_message_form,
    campaign_preview,
    campaign_review,
    campaign_workbench,
    customer_message,
    customer_review,
    order_review,
    order_workbench,
    owner_dashboard,
    product_catalog,
    catalog_plan_form,
    catalog_plan_review,
    reports_center,
    reports_export,
    revenue_control_center,
    service_bulk_soft_delete_missing,
    service_reconcile,
    service_review,
    service_soft_delete_missing,
    service_workbench,
    setup_center,
    setup_wizard_index,
    setup_wizard_step,
    support_review,
    support_workbench,
)
from store.admin_panel_center.views import (
    panel_center_capabilities,
    panel_center_detail,
    panel_center_form,
    panel_center_alerts_dry_run,
    panel_center_inbounds,
    panel_center_index,
    panel_center_panel_alert_disable,
    panel_center_panel_alert_enable,
    panel_center_panel_alerts_dry_run,
    panel_center_sync,
    panel_center_test,
)
from store.admin_panel_center.routing_views import (
    routing_detail,
    routing_index,
)
from store.admin_cup_center.views import (
    cup_center_add_existing,
    cup_center_add_inventory,
    cup_center_add_manual,
    cup_center_create_from_inbound,
    cup_center_detail,
    cup_center_item_link_secret,
    cup_center_index,
    cup_center_new,
    cup_center_preview,
    cup_center_quick_build,
    cup_center_quick_result,
    cup_center_rebuild,
)
from store.admin_config_inventory import (
    config_inventory_dashboard,
    config_inventory_import,
)
from store.admin_plan_fulfillment import (
    plan_fulfillment_dashboard,
    plan_fulfillment_plan,
    plan_fulfillment_plans,
    plan_fulfillment_recipe,
    plan_fulfillment_recipe_preview,
    plan_fulfillment_recipe_simulate,
)
from store.admin_staff import (
    staff_access_center,
    staff_create,
    staff_edit,
    staff_password,
    staff_review,
    staff_role_detail,
    staff_roles,
)

urlpatterns = [
    path('health', health, name='health_no_slash'),
    path('health/', health, name='health'),
    path(
        'admin/card-receipts-report/',
        admin.site.admin_view(card_receipts_report),
        name='admin_card_receipts_report',
    ),
    path(
        'admin/store/setup/',
        admin.site.admin_view(setup_center),
        name='admin_store_setup_center',
    ),
    path(
        'admin/store/config-inventory/',
        admin.site.admin_view(config_inventory_dashboard),
        name='admin_store_config_inventory',
    ),
    path(
        'admin/store/config-inventory/import/',
        admin.site.admin_view(config_inventory_import),
        name='admin_store_config_inventory_import',
    ),
    path(
        'admin/store/plan-fulfillment/',
        admin.site.admin_view(plan_fulfillment_dashboard),
        name='admin_store_plan_fulfillment',
    ),
    path(
        'admin/store/plan-fulfillment/plans/',
        admin.site.admin_view(plan_fulfillment_plans),
        name='admin_store_plan_fulfillment_plans',
    ),
    path(
        'admin/store/plan-fulfillment/plan/<int:plan_id>/',
        admin.site.admin_view(plan_fulfillment_plan),
        name='admin_store_plan_fulfillment_plan',
    ),
    path(
        'admin/store/plan-fulfillment/recipe/<int:recipe_id>/',
        admin.site.admin_view(plan_fulfillment_recipe),
        name='admin_store_plan_fulfillment_recipe',
    ),
    path(
        'admin/store/plan-fulfillment/recipe/<int:recipe_id>/preview/',
        admin.site.admin_view(plan_fulfillment_recipe_preview),
        name='admin_store_plan_fulfillment_recipe_preview',
    ),
    path(
        'admin/store/plan-fulfillment/recipe/<int:recipe_id>/simulate/',
        admin.site.admin_view(plan_fulfillment_recipe_simulate),
        name='admin_store_plan_fulfillment_recipe_simulate',
    ),
    path(
        'admin/store/backups/',
        admin.site.admin_view(backup_center),
        name='admin_store_backup_center',
    ),
    path(
        'admin/store/backups/create/',
        admin.site.admin_view(backup_create),
        name='admin_store_backup_create',
    ),
    path(
        'admin/store/backups/<int:job_id>/download/',
        admin.site.admin_view(backup_download),
        name='admin_store_backup_download',
    ),
    path(
        'admin/store/backups/<int:job_id>/delete/',
        admin.site.admin_view(backup_delete),
        name='admin_store_backup_delete',
    ),
    path(
        'admin/store/restore/upload/',
        admin.site.admin_view(restore_upload),
        name='admin_store_restore_upload',
    ),
    path(
        'admin/store/restore/<int:restore_id>/',
        admin.site.admin_view(restore_detail),
        name='admin_store_restore_detail',
    ),
    path(
        'admin/store/restore/<int:restore_id>/validate/',
        admin.site.admin_view(restore_validate),
        name='admin_store_restore_validate',
    ),
    path(
        'admin/store/restore/<int:restore_id>/command/',
        admin.site.admin_view(restore_command),
        name='admin_store_restore_command',
    ),
    path(
        'admin/store/dashboard/',
        admin.site.admin_view(owner_dashboard),
        name='admin_store_owner_dashboard',
    ),
    path(
        'admin/store/panel-center/',
        admin.site.admin_view(panel_center_index),
        name='admin_store_panel_center',
    ),
    path(
        'admin/store/cup-center/',
        admin.site.admin_view(cup_center_index),
        name='admin_store_cup_center',
    ),
    path(
        'admin/store/cup-center',
        admin.site.admin_view(cup_center_index),
    ),
    path(
        'admin/store/cup-center/new/',
        admin.site.admin_view(cup_center_new),
        name='admin_store_cup_center_new',
    ),
    path(
        'admin/store/cup-center/new',
        admin.site.admin_view(cup_center_new),
    ),
    path(
        'admin/store/cup-center/quick-build/',
        admin.site.admin_view(cup_center_quick_build),
        name='admin_store_cup_center_quick_build',
    ),
    path(
        'admin/store/cup-center/quick-build',
        admin.site.admin_view(cup_center_quick_build),
    ),
    path(
        'admin/store/cup-center/quick-build/<int:cup_id>/result/',
        admin.site.admin_view(cup_center_quick_result),
        name='admin_store_cup_center_quick_result',
    ),
    path(
        'admin/store/cup-center/quick-build/<int:cup_id>/result',
        admin.site.admin_view(cup_center_quick_result),
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/',
        admin.site.admin_view(cup_center_detail),
        name='admin_store_cup_center_detail',
    ),
    path(
        'admin/store/cup-center/<int:cup_id>',
        admin.site.admin_view(cup_center_detail),
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/add-existing-links/',
        admin.site.admin_view(cup_center_add_existing),
        name='admin_store_cup_center_add_existing',
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/add-existing-links',
        admin.site.admin_view(cup_center_add_existing),
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/items/<int:item_id>/link-secret/',
        admin.site.admin_view(cup_center_item_link_secret),
        name='admin_store_cup_center_item_link_secret',
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/add-inventory-assets/',
        admin.site.admin_view(cup_center_add_inventory),
        name='admin_store_cup_center_add_inventory',
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/add-inventory-assets',
        admin.site.admin_view(cup_center_add_inventory),
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/add-manual-links/',
        admin.site.admin_view(cup_center_add_manual),
        name='admin_store_cup_center_add_manual',
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/add-manual-links',
        admin.site.admin_view(cup_center_add_manual),
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/create-from-inbound/',
        admin.site.admin_view(cup_center_create_from_inbound),
        name='admin_store_cup_center_create_from_inbound',
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/create-from-inbound',
        admin.site.admin_view(cup_center_create_from_inbound),
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/preview/',
        admin.site.admin_view(cup_center_preview),
        name='admin_store_cup_center_preview',
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/preview',
        admin.site.admin_view(cup_center_preview),
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/rebuild/',
        admin.site.admin_view(cup_center_rebuild),
        name='admin_store_cup_center_rebuild',
    ),
    path(
        'admin/store/cup-center/<int:cup_id>/rebuild',
        admin.site.admin_view(cup_center_rebuild),
    ),
    path(
        'admin/store/panel-center/new/',
        admin.site.admin_view(panel_center_form),
        name='admin_store_panel_center_new',
    ),
    path(
        'admin/store/panel-center/alerts/dry-run/',
        admin.site.admin_view(panel_center_alerts_dry_run),
        name='admin_store_panel_center_alerts_dry_run',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/',
        admin.site.admin_view(panel_center_detail),
        name='admin_store_panel_center_detail',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/edit/',
        admin.site.admin_view(panel_center_form),
        name='admin_store_panel_center_edit',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/capabilities/',
        admin.site.admin_view(panel_center_capabilities),
        name='admin_store_panel_center_capabilities',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/inbounds/',
        admin.site.admin_view(panel_center_inbounds),
        name='admin_store_panel_center_inbounds',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/test/',
        admin.site.admin_view(panel_center_test),
        name='admin_store_panel_center_test',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/alerts/dry-run/',
        admin.site.admin_view(panel_center_panel_alerts_dry_run),
        name='admin_store_panel_center_panel_alerts_dry_run',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/alerts/enable/',
        admin.site.admin_view(panel_center_panel_alert_enable),
        name='admin_store_panel_center_panel_alert_enable',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/alerts/disable/',
        admin.site.admin_view(panel_center_panel_alert_disable),
        name='admin_store_panel_center_panel_alert_disable',
    ),
    path(
        'admin/store/panel-center/<int:panel_id>/sync/',
        admin.site.admin_view(panel_center_sync),
        name='admin_store_panel_center_sync',
    ),
    path(
        'admin/store/panel-center/routing/',
        admin.site.admin_view(routing_index),
        name='admin_store_panel_center_routing',
    ),
    path(
        'admin/store/panel-center/routing/<int:plan_id>/',
        admin.site.admin_view(routing_detail),
        name='admin_store_panel_center_routing_detail',
    ),
    path(
        'admin/store/catalog/',
        admin.site.admin_view(product_catalog),
        name='admin_store_catalog',
    ),
    path(
        'admin/store/catalog/plans/new/',
        admin.site.admin_view(catalog_plan_form),
        name='admin_store_catalog_plan_new',
    ),
    path(
        'admin/store/catalog/plans/<int:plan_id>/',
        admin.site.admin_view(catalog_plan_review),
        name='admin_store_catalog_plan_review',
    ),
    path(
        'admin/store/catalog/plans/<int:plan_id>/edit/',
        admin.site.admin_view(catalog_plan_form),
        name='admin_store_catalog_plan_edit',
    ),
    path(
        'admin/store/revenue/control/',
        admin.site.admin_view(revenue_control_center),
        name='admin_store_revenue_control',
    ),
    path(
        'admin/store/reports/',
        admin.site.admin_view(reports_center),
        name='admin_store_reports_center',
    ),
    path(
        'admin/store/reports/export/',
        admin.site.admin_view(reports_export),
        name='admin_store_reports_export',
    ),
    path(
        'admin/store/campaigns/',
        admin.site.admin_view(campaign_workbench),
        name='admin_store_campaign_workbench',
    ),
    path(
        'admin/store/campaigns/new/',
        admin.site.admin_view(campaign_message_form),
        name='admin_store_campaign_new',
    ),
    path(
        'admin/store/campaigns/<int:campaign_id>/',
        admin.site.admin_view(campaign_review),
        name='admin_store_campaign_review',
    ),
    path(
        'admin/store/campaigns/<int:campaign_id>/edit/',
        admin.site.admin_view(campaign_message_form),
        name='admin_store_campaign_edit',
    ),
    path(
        'admin/store/campaigns/<int:campaign_id>/audience/',
        admin.site.admin_view(campaign_audience),
        name='admin_store_campaign_audience',
    ),
    path(
        'admin/store/campaigns/<int:campaign_id>/preview/',
        admin.site.admin_view(campaign_preview),
        name='admin_store_campaign_preview',
    ),
    path(
        'admin/store/campaigns/<int:campaign_id>/confirm/',
        admin.site.admin_view(campaign_confirm),
        name='admin_store_campaign_confirm',
    ),
    path(
        'admin/store/campaigns/<int:campaign_id>/export/',
        admin.site.admin_view(campaign_export),
        name='admin_store_campaign_export',
    ),
    path(
        'admin/store/staff/',
        admin.site.admin_view(staff_access_center),
        name='admin_store_staff_access',
    ),
    path(
        'admin/store/staff/new/',
        admin.site.admin_view(staff_create),
        name='admin_store_staff_new',
    ),
    path(
        'admin/store/staff/roles/',
        admin.site.admin_view(staff_roles),
        name='admin_store_staff_roles',
    ),
    path(
        'admin/store/staff/roles/<slug:role_key>/',
        admin.site.admin_view(staff_role_detail),
        name='admin_store_staff_role_detail',
    ),
    path(
        'admin/store/staff/<int:user_id>/',
        admin.site.admin_view(staff_review),
        name='admin_store_staff_review',
    ),
    path(
        'admin/store/staff/<int:user_id>/edit/',
        admin.site.admin_view(staff_edit),
        name='admin_store_staff_edit',
    ),
    path(
        'admin/store/staff/<int:user_id>/password/',
        admin.site.admin_view(staff_password),
        name='admin_store_staff_password',
    ),
    path(
        'admin/store/orders/workbench/',
        admin.site.admin_view(order_workbench),
        name='admin_store_order_workbench',
    ),
    path(
        'admin/store/orders/<int:order_id>/review/',
        admin.site.admin_view(order_review),
        name='admin_store_order_review',
    ),
    path(
        'admin/store/support/workbench/',
        admin.site.admin_view(support_workbench),
        name='admin_store_support_workbench',
    ),
    path(
        'admin/store/support/<int:support_id>/review/',
        admin.site.admin_view(support_review),
        name='admin_store_support_review',
    ),
    path(
        'admin/store/services/workbench/',
        admin.site.admin_view(service_workbench),
        name='admin_store_service_workbench',
    ),
    path(
        'admin/store/services/reconcile/',
        admin.site.admin_view(service_reconcile),
        name='admin_store_services_reconcile',
    ),
    path(
        'admin/store/services/reconciliation/soft-delete-missing/',
        admin.site.admin_view(service_bulk_soft_delete_missing),
        name='admin_store_services_reconciliation_soft_delete_missing',
    ),
    path(
        'admin/store/services/<int:vpn_client_id>/review/',
        admin.site.admin_view(service_review),
        name='admin_store_service_review',
    ),
    path(
        'admin/store/services/<int:vpn_client_id>/soft-delete-missing/',
        admin.site.admin_view(service_soft_delete_missing),
        name='admin_store_service_soft_delete_missing',
    ),
    path(
        'admin/store/customers/<int:customer_id>/review/',
        admin.site.admin_view(customer_review),
        name='admin_store_customer_review',
    ),
    path(
        'admin/store/customers/<int:customer_id>/message/',
        admin.site.admin_view(customer_message),
        name='admin_store_customer_message',
    ),
    path(
        'admin/store/setup/wizard/',
        admin.site.admin_view(setup_wizard_index),
        name='admin_store_setup_wizard',
    ),
    path(
        'admin/store/setup/wizard/store/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'store')),
        name='admin_store_setup_wizard_store',
    ),
    path(
        'admin/store/setup/wizard/payment/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'payment')),
        name='admin_store_setup_wizard_payment',
    ),
    path(
        'admin/store/setup/wizard/telegram/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'telegram')),
        name='admin_store_setup_wizard_telegram',
    ),
    path(
        'admin/store/setup/wizard/telegram-proxy/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'telegram-proxy')),
        name='admin_store_setup_wizard_telegram_proxy',
    ),
    path(
        'admin/store/setup/wizard/panel/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'panel')),
        name='admin_store_setup_wizard_panel',
    ),
    path(
        'admin/store/setup/wizard/inbounds/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'inbounds')),
        name='admin_store_setup_wizard_inbounds',
    ),
    path(
        'admin/store/setup/wizard/plans/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'plans')),
        name='admin_store_setup_wizard_plans',
    ),
    path(
        'admin/store/setup/wizard/routes/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'routes')),
        name='admin_store_setup_wizard_routes',
    ),
    path(
        'admin/store/setup/wizard/review/',
        admin.site.admin_view(lambda request: setup_wizard_step(request, 'review')),
        name='admin_store_setup_wizard_review',
    ),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('payments.urls')),
    path('', include('store.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
