# Generated by Django 6.0.4 on 2026-10-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0068_order_automation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCollector',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=32)),
                ('lease_until', models.DateTimeField(null=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('summary', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True, null=True)),
                ('entitlement', models.CharField(default='unknown', max_length=24)),
                ('reason', models.CharField(default='not_observed', max_length=48)),
                ('counters', models.JSONField(default=dict)),
                ('continuous_since', models.DateTimeField(null=True)),
                ('last_activity_start', models.DateTimeField(null=True)),
                ('last_activity_at', models.DateTimeField(null=True)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('ended_at', models.DateTimeField(null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('interval_start', models.DateTimeField(null=True)),
                ('delta_bytes', models.PositiveBigIntegerField(null=True)),
                ('quality', models.CharField(max_length=48)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='customer_activity.purchaseactivity')),
            ],
            options={
                'indexes': [models.Index(fields=['observed_at'], name='activity_observed_idx')],
                'constraints': [models.UniqueConstraint(fields=('purchase', 'observed_at'), name='activity_purchase_sample_unique')],
            },
        ),
    ]
