# Generated by Django 6.0.4 on 2026-10-03 12:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_activity', '0001_initial'),
        ('store', '0068_order_automation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseactivity',
            name='cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OutreachSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('off', 'خاموش'), ('preview', 'پیش\u200cنمایش'), ('live', 'ارسال فعال')], default='preview', max_length=12)),
                ('inactivity_enabled', models.BooleanField(default=True)),
                ('renewal_enabled', models.BooleanField(default=True)),
                ('daily_limit', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('start_hour', models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(23)])),
                ('end_hour', models.PositiveSmallIntegerField(default=21, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('activated_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(null=True)),
                ('summary', models.JSONField(default=dict)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=24)),
                ('status', models.CharField(choices=[('preview', 'پیش\u200cنمایش'), ('ready', 'در انتظار ارسال'), ('sending', 'در حال ارسال'), ('sent', 'ارسال شد'), ('uncertain', 'نتیجه نامشخص؛ نیازمند بررسی'), ('failed', 'ردشده توسط تلگرام'), ('cancelled', 'شرایط دیگر برقرار نیست')], db_index=True, default='preview', max_length=12)),
                ('body', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('message_id', models.CharField(blank=True, max_length=40)),
                ('bot_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.botuser')),
                ('converted_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_purchase_outreach', to='store.order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_outreach', to='store.order')),
                ('support_conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.supportconversation')),
            ],
            options={
                'indexes': [models.Index(fields=['claimed_at', 'status'], name='outreach_claimed_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'cycle', 'kind'), name='outreach_purchase_stage_unique')],
            },
        ),
        migrations.CreateModel(
            name='OutreachPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'customer'), name='outreach_customer_store_unique')],
            },
        ),
    ]
